Repository microsoft/botbuilder-dotnet, pull requests merged in 2018-04, with the labels that each got.

#369 Add doc XML to ITurnContext.
  libraries/Microsoft.Bot.Builder.Core/ITurnContext.cs
  libraries/Microsoft.Bot.Builder.Core/TurnContext.cs
Labels: docs

#370 Add doc XML to BotFrameworkAdapter
  libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
Labels: docs

#378 Add doc XML to MessageFactory
  libraries/Microsoft.Bot.Builder.Core.Extensions/MessageFactory.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/Microsoft.Bot.Builder.Core.Extensions.csproj
Labels: docs

#382 Add doc XML to integration core library
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkOptions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs
Labels: docs

#383 Add [and edit] doc XML to critical classes in the prompts library.
  libraries/Microsoft.Bot.Builder.Prompts/BasePrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/PromptValidator.cs
  libraries/Microsoft.Bot.Builder.Prompts/TextPrompt.cs
Labels: docs

#386 Rename OnReceiveActivity to OnTurn, as part of the M3 changes.
  libraries/Microsoft.Bot.Builder.Ai/LocaleConverterMiddleware.cs
  libraries/Microsoft.Bot.Builder.Ai/QnAMakerMiddleware.cs
  libraries/Microsoft.Bot.Builder.Ai/TranslationMiddleware.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/BotState.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/CatchExceptionMiddleware.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/IntentRecognizerMiddleware.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/ShowTypingMiddleware.cs
  libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs
  libraries/Microsoft.Bot.Builder.Core/IBot.cs
  libraries/Microsoft.Bot.Builder.Core/IMiddleware.cs
  libraries/Microsoft.Bot.Builder.Core/MiddlewareSet.cs
  libraries/Microsoft.Bot.Builder.LUIS/LuisRecognizerMiddleware.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandlerBase.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandlerBase.cs
  samples/AlarmBot-Cards/AlarmBot.cs
  samples/AlarmBot/AlarmBot.cs
  samples/Microsoft.Bot.Samples.Ai.Luis.Translator/LuisTranslatorBot.cs
  samples/Microsoft.Bot.Samples.Ai.Luis/LuisBot.cs
  samples/Microsoft.Bot.Samples.Ai.QnA.Translator/QnAMakerBot.cs
  samples/Microsoft.Bot.Samples.Ai.QnA/QnAMakerBot.cs
  samples/Microsoft.Bot.Samples.EchoBot-AspNetCore/EchoBot.cs
  samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/EchoBot.cs
  samples/Microsoft.Bot.Samples.EchoBot-Console/EchoBot.cs
  samples/Microsoft.Bot.Samples.EchoBot-Console/Program.cs
  tests/Microsoft.Bot.Builder.Core.Tests/BotAdapterBracketingTest.cs
  tests/Microsoft.Bot.Builder.Core.Tests/BotAdapterTests.cs
  tests/Microsoft.Bot.Builder.Core.Tests/MiddlewareSetTests.cs
Labels: enhancement

#387 ASP.NET Integration API Documentation Comments
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkOptions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkPaths.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/IBotConfigurationBuilder.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ServiceCollectionExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkConfigurationBuilder.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkOptions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkPaths.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs
Labels: docs

#399 Add documentation config
  Microsoft.Bot.Builder.sln
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Microsoft.Bot.Builder.Ai.LUIS.csproj
  libraries/Microsoft.Bot.Builder.Ai.QnA/Microsoft.Bot.Builder.Ai.QnA.csproj
  libraries/Microsoft.Bot.Builder.Ai.Translation/Microsoft.Bot.Builder.Ai.Translation.csproj
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic.csproj
  libraries/Microsoft.Bot.Builder.Classic/RView/RView.csproj
  libraries/Microsoft.Bot.Builder.Core.Extensions/Microsoft.Bot.Builder.Core.Extensions.csproj
  libraries/Microsoft.Bot.Builder.Core/Microsoft.Bot.Builder.Core.csproj
  libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj
  libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj
  libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
  libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
  libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
  samples/AlarmBot-Cards/AlarmBot-Cards.csproj
  samples/AlarmBot/AlarmBot.csproj
  samples/Microsoft.Bot.Samples.Ai.Luis.Translator/Microsoft.Bot.Samples.Ai.Luis.Translator.csproj
  samples/Microsoft.Bot.Samples.Ai.Luis/Microsoft.Bot.Samples.Ai.Luis.csproj
  samples/Microsoft.Bot.Samples.Ai.QnA.Translator/Microsoft.Bot.Samples.Ai.QnA.Translator.csproj
  samples/Microsoft.Bot.Samples.Ai.QnA/Microsoft.Bot.Samples.Ai.QnA.csproj
  samples/Microsoft.Bot.Samples.Connector.EchoBot/Microsoft.Bot.Samples.Connector.EchoBot.csproj
  samples/Microsoft.Bot.Samples.EchoBot-AspNetCore/Microsoft.Bot.Samples.EchoBot-AspNetCore.csproj
  samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/Microsoft.Bot.Samples.EchoBot-AspNetWebApi.csproj
  samples/Microsoft.Bot.Samples.EchoBot-Console/Microsoft.Bot.Samples.EchoBot-Console.csproj
  tests/FormTest/FormTest.csproj
  tests/Microsoft.Bot.Builder.Ai.LUIS.Tests/Microsoft.Bot.Builder.Ai.LUIS.Tests.csproj
  tests/Microsoft.Bot.Builder.Ai.QnA.Tests/Microsoft.Bot.Builder.Ai.QnA.Tests.csproj
  tests/Microsoft.Bot.Builder.Ai.Translation.Tests/Microsoft.Bot.Builder.Ai.Translation.Tests.csproj
  tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj
  tests/Microsoft.Bot.Builder.Classic.Tests/Microsoft.Bot.Builder.Classic.Tests.csproj
  tests/Microsoft.Bot.Builder.Core.Extensions.Tests/Microsoft.Bot.Builder.Core.Extensions.Tests.csproj
  tests/Microsoft.Bot.Builder.Core.Tests/Microsoft.Bot.Builder.Core.Tests.csproj
  tests/Microsoft.Bot.Builder.Prompts.Tests/Microsoft.Bot.Builder.Prompts.Tests.csproj
  tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj
  tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
  tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
  tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj
Labels: docs

#400 Removed old QnA Maker Test File
  tests/Microsoft.Bot.Builder.Ai.QnA.Tests/Microsoft.Bot.Builder.Ai.Tests.csproj
Labels: build

#394 Initial Implementation of Invoke
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Builder/InvokeResponse.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandlerBase.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotProactiveMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandlerBase.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotProactiveMessageHandler.cs
  samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/Microsoft.Bot.Samples.EchoBot-AspNetWebApi.csproj
  samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/Properties/AssemblyInfo.cs
  samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/Web.config
  samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/packages.config
Labels: enhancement

#417 Add support for BotAppId via proactive endpoint
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotProactiveMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotProactiveMessageHandler.cs
Labels: proactive

#424 Do not set the Responded Flag based on TraceActivities.
  libraries/Microsoft.Bot.Builder.Core/TurnContext.cs
  tests/Microsoft.Bot.Builder.Core.Tests/TurnContextTests.cs
Labels: bug

#426 Make Transcript tests pass on a "First time run" scenario
  tests/Microsoft.Bot.Builder.Azure.Tests/BlobTranscriptTests.cs
Labels: bug

#388 Azure Blob Storage Provider
  libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  tests/Microsoft.Bot.Builder.Azure.Tests/BloblStorageTests.cs
Labels: state-management

#425 Remove use of dynamic from Storage APIs
  Microsoft.Bot.Builder.Dialogs.Tests/DialogTests.cs
  libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/AzureTableStorage.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/BotState.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/EntityRecognizers.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/FileStorage.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/FlexObject.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/IStorage.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/MemoryStorage.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs
  samples/AlarmBot-Cards/EntityRecognizers.cs
  samples/AlarmBot-Cards/Models/State.cs
  samples/AlarmBot-Cards/RegExpRecognizerMiddleware.cs
  samples/AlarmBot-Cards/Topics/AddAlarmTopic.cs
  samples/AlarmBot-Cards/Topics/DeleteAlarmTopic.cs
  samples/AlarmBot/EntityRecognizers.cs
  samples/AlarmBot/Models/State.cs
  samples/AlarmBot/RegExpRecognizerMiddleware.cs
  samples/AlarmBot/Topics/AddAlarmTopic.cs
  samples/AlarmBot/Topics/DeleteAlarmTopic.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/BlobStorageTests.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/TableStorageTests.cs
  tests/Microsoft.Bot.Builder.Core.Extensions.Tests/BotStateTests.cs
  tests/Microsoft.Bot.Builder.Core.Extensions.Tests/FileStorageTests.cs
  tests/Microsoft.Bot.Builder.Core.Extensions.Tests/FlexObjectTests.cs
  tests/Microsoft.Bot.Builder.Core.Extensions.Tests/MemoryStorageTests.cs
  tests/Microsoft.Bot.Builder.Core.Extensions.Tests/StorageBaseTests.cs
  tests/Microsoft.Bot.Builder.Prompts.Tests/NumberPromptTests.cs
  tests/Microsoft.Bot.Builder.Prompts.Tests/TextPromptTests.cs
Labels: enhancement

#384 CosmosDB Storage Provider
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
Labels: state-management

#449 Update Autofac to version 4.7.1
  libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic.csproj
  libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/packages.config
  tests/FormTest/FormTest.csproj
  tests/FormTest/packages.config
  tests/Microsoft.Bot.Builder.Classic.Tests/BotTests.cs
  tests/Microsoft.Bot.Builder.Classic.Tests/ChainTests.cs
  tests/Microsoft.Bot.Builder.Classic.Tests/DialogModuleTests.cs
  tests/Microsoft.Bot.Builder.Classic.Tests/DisableTests.cs
  tests/Microsoft.Bot.Builder.Classic.Tests/DispatchDialogTests .cs
  tests/Microsoft.Bot.Builder.Classic.Tests/EndConversationTests.cs
  tests/Microsoft.Bot.Builder.Classic.Tests/ExceptionTests.cs
  tests/Microsoft.Bot.Builder.Classic.Tests/LuisTests.cs
  tests/Microsoft.Bot.Builder.Classic.Tests/Microsoft.Bot.Builder.Classic.Tests.csproj
  tests/Microsoft.Bot.Builder.Classic.Tests/ScorableDialogTests.cs
  tests/Microsoft.Bot.Builder.Classic.Tests/Script.cs
Labels: enhancement

#450 Console Adapter Echo Bot with State Counter
  AspNetCore-EchoBot-With-State/AspNetCore-EchoBot-With-State.csproj
  AspNetCore-EchoBot-With-State/EchoBot.cs
  AspNetCore-EchoBot-With-State/EchoState.cs
  AspNetCore-EchoBot-With-State/Program.cs
  AspNetCore-EchoBot-With-State/Startup.cs
  AspNetCore-EchoBot-With-State/appsettings.json
  AspNetCore-EchoBot-With-State/readme.md
  AspNetCore-EchoBot-With-State/wwwroot/default.htm
  Microsoft.Bot.Builder.Samples.sln
  samples-final/Console-EchoBot-With-State/Console-EchoBot-With-State.csproj
  samples-final/Console-EchoBot-With-State/Program.cs
Labels: samples

#462 Clm/move samples to right place
  Microsoft.Bot.Builder.Samples.sln
  samples-final/AspNetCore-EchoBot-With-State/AspNetCore-EchoBot-With-State.csproj
  samples-final/AspNetCore-EchoBot-With-State/EchoBot.cs
  samples-final/AspNetCore-EchoBot-With-State/EchoState.cs
  samples-final/AspNetCore-EchoBot-With-State/Program.cs
  samples-final/AspNetCore-EchoBot-With-State/Startup.cs
  samples-final/AspNetCore-EchoBot-With-State/appsettings.json
  samples-final/AspNetCore-EchoBot-With-State/readme.md
  samples-final/AspNetCore-EchoBot-With-State/wwwroot/default.htm
Labels: samples

#463 Removed System.Dynamic dependency from Core.Extensions.
  libraries/Microsoft.Bot.Builder.Core.Extensions/Microsoft.Bot.Builder.Core.Extensions.csproj
Labels: enhancement

#468 Fix NullReferenceException when calling BotFrameworkAdapter::ContinueConversation
  libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Labels: P0, proactive

#473 Update docXML for types in the Ai.LUIS namespace
  libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisRecognizer.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisRecognizerMiddleware.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisRecognizerOptions.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/RecognizerResult.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/RecognizerResultExtensions.cs
Labels: docs

#469 Update the `documentation` build configuration
  Microsoft.Bot.Builder.sln
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Microsoft.Bot.Builder.Ai.LUIS.csproj
  libraries/Microsoft.Bot.Builder.Ai.QnA/Microsoft.Bot.Builder.Ai.QnA.csproj
  libraries/Microsoft.Bot.Builder.Ai.Translation/Microsoft.Bot.Builder.Ai.Translation.csproj
  libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
Labels: docs

#487 docXML updates for Ai.QnAMaker and Ai.Translation namespaces
  libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMaker.cs
  libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMakerMiddleware.cs
  libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMakerMiddlewareOptions.cs
  libraries/Microsoft.Bot.Builder.Ai.Translation/TranslationMiddleware.cs
  libraries/Microsoft.Bot.Builder.Ai.Translation/Translator.cs
Labels: docs

#484 Change some scopes, per issue #472
  Microsoft.Bot.Builder.sln
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptDelegates.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandler.cs
Labels: docs, enhancement

#489 Fix incorrect Header to show the protocol version
  libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
Labels: bug

#490 Align BotFramework Send Behavior with Node per #464
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Labels: P1, bug

#497 Add docXML for some state and storage classes
  libraries/Microsoft.Bot.Builder.Azure/AzureTableStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/BotState.cs
Labels: docs
