Repository microsoft/botbuilder-dotnet, pull requests merged in 2018-06, with the labels that each got.

#631 Loosen tolerances on Unit test that sometimes fails on Build Server
  tests/Microsoft.Bot.Builder.Azure.Tests/BlobStorageTests.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/BlobTranscriptTests.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/TableStorageTests.cs
  tests/Microsoft.Bot.Builder.Core.Extensions.Tests/ShowTyping_MiddlewareTests.cs
Labels: Approved, build

#646 EndorsementsRetriever perf, hardening and unit test coverage
  libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsRetrieverTests.cs
  tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
Labels: perf, testing

#655 Token Endorsements
  libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/EndorsementsValidator.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsValidatorTests.cs
  tests/Microsoft.Bot.Connector.Tests/JwtTokenValidationTests.cs
Labels: bug

#670 Move ConfigurationCredentialProvider out of core
  libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationCredentialProvider.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/ConfigurationCredentialProvider.cs
Labels: integration

#674 Remove reference to removed assembly from sample
  samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi/Microsoft.Bot.Samples.EchoBot-AspNetWebApi.csproj
Labels: build

#707 Add/update doc XML for test flow/adapter
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs
Labels: docs

#708 Fix new doc XML issues introduced recently
  libraries/Microsoft.Bot.Builder.Ai.Translation/TranslationMiddleware.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkConfigurationBuilder.cs
Labels: docs

#715 Clone .editorConfig from the Rosyln team
  .editorconfig
Labels: build, enhancement
