Repository microsoft/botbuilder-dotnet, pull requests merged in 2018-02, with the labels that each got.

#92 Addresses Issue #76. Normalized "Reply" with JS codebase.
  libraries/Microsoft.Bot.Builder/BotContext.cs
  libraries/Microsoft.Bot.Builder/IBotContext.cs
  tests/Microsoft.Bot.Builder.Tests/BotContext_Tests.cs
Labels: enhancement

#100 Renamed PostActivity to SendActivity throughout the BotBuilder layer.
  libraries/Microsoft.Bot.Builder.Ai/TranslationMiddleware.cs
  libraries/Microsoft.Bot.Builder.BotFramework/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Builder/Adapters/ActivityAdapterBase.cs
  libraries/Microsoft.Bot.Builder/Adapters/ConsoleAdapter.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Builder/Bot.cs
  libraries/Microsoft.Bot.Builder/BotContext.cs
  libraries/Microsoft.Bot.Builder/BotStateManager.cs
  libraries/Microsoft.Bot.Builder/IBotContext.cs
  libraries/Microsoft.Bot.Builder/Middleware/IMiddleware.cs
  libraries/Microsoft.Bot.Builder/Middleware/MiddlewareSet.cs
  libraries/Microsoft.Bot.Builder/Middleware/PostToAdapterMiddleware.cs
  libraries/Microsoft.Bot.Builder/Middleware/TemplateManager.cs
  samples/Microsoft.Bot.Samples.CustomMiddleware/Middleware/ExampleMiddleware.cs
  tests/Microsoft.Bot.Builder.Tests/BotContext_Tests.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_ComposibilityTests.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_PostActivityTests.cs
Labels: enhancement

#115 Added Conversation Binding to outgoing messages, similar to JS
  libraries/Microsoft.Bot.Builder/Assertions.cs
  libraries/Microsoft.Bot.Builder/Bot.cs
  libraries/Microsoft.Bot.Builder/Middleware/BindOutgoingResponsesMiddlware.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_BindOutoingResponsesTests.cs
Labels: bug

#119 Fixed, per discussion with Gabo
  libraries/Microsoft.Bot.Builder/Middleware/TemplateManager.cs
Labels: bug

#118 Simplified Construction and Ordering of Bot/MiddlwareSet Interactions
  libraries/Microsoft.Bot.Builder/Bot.cs
  libraries/Microsoft.Bot.Builder/BotContext.cs
  libraries/Microsoft.Bot.Builder/IBotContext.cs
  libraries/Microsoft.Bot.Builder/Middleware/MiddlewareSet.cs
  samples/AlarmBot-Cards/Controllers/MessagesController.cs
  samples/AlarmBot/Controllers/MessagesController.cs
  samples/Microsoft.Bot.Samples.Ai.Luis/Controllers/MessagesController.cs
  samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs
  samples/Microsoft.Bot.Samples.CustomMiddleware/Controllers/MessagesController.cs
  samples/Microsoft.Bot.Samples.EchoBot-Console/Program.cs
  samples/Microsoft.Bot.Samples.Simplified.Asp/BotController.cs
  tests/Microsoft.Bot.Builder.Ai.Tests/LuisRecognizerTests.cs
  tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerTests.cs
  tests/Microsoft.Bot.Builder.Tests/Adapter_TestAdapterTests.cs
  tests/Microsoft.Bot.Builder.Tests/BotContext_Tests.cs
  tests/Microsoft.Bot.Builder.Tests/ContextExtensionTests.cs
  tests/Microsoft.Bot.Builder.Tests/Intent_RegExRecognizerTests.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_BindOutoingResponsesTests.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_ComposibilityTests.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_ContextCreatedTests.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_PostActivityTests.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_ReceiveActivityTests.cs
  tests/Microsoft.Bot.Builder.Tests/State_BasicTests.cs
  tests/Microsoft.Bot.Builder.Tests/Templates_TemplateManagerTests.cs
Labels: bug, enhancement

#122 QnAMakerMiddleware with static HttpClient
  libraries/Microsoft.Bot.Builder.Ai/QnAMakerMiddleware.cs
  libraries/Microsoft.Bot.Builder/Bot.cs
  samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs
  tests/Microsoft.Bot.Builder.Ai.Tests/QnAMakerTests.cs
Labels: bug

#131 process expected activities
  samples/Microsoft.Bot.Samples.Simplified.Asp/BotController.cs
Labels: bug

#133 Reuse of HttpClient throughout the Stack.
  libraries/Microsoft.Bot.Builder.Ai/TranslationMiddleware.cs
  libraries/Microsoft.Bot.Builder.Ai/Translator.cs
  libraries/Microsoft.Bot.Builder.BotFramework/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Connector.AspNetCore/BotAuthenticationHandler.cs
  libraries/Microsoft.Bot.Connector/AttachmentsEx.cs
  libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs
  samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs
  samples/Microsoft.Bot.Samples.Simplified.Asp/appsettings.json
Labels: enhancement

#140 Pass exceptions on Faulted Tasks as inner Exceptions.
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  tests/Microsoft.Bot.Builder.Tests/Adapter_TestAdapterTests.cs
Labels: bug, enhancement, help wanted

#158 Always run the SendPipeline, even if there's nothing to send.
  libraries/Microsoft.Bot.Builder/Bot.cs
  tests/Microsoft.Bot.Builder.Tests/BotContext_Tests.cs
  tests/Microsoft.Bot.Builder.Tests/Bot_FunctionalTests.cs
Labels: enhancement

#159 Refactor BotStateManager into User and Conversation components
  libraries/Microsoft.Bot.Builder.BotFramework/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Builder/BotState.cs
  libraries/Microsoft.Bot.Builder/BotStateManager.cs
  libraries/Microsoft.Bot.Builder/Middleware/ConversationStateManagerMiddleware.cs
  libraries/Microsoft.Bot.Builder/Middleware/UserStateManagerMiddleware.cs
  samples/AlarmBot-Cards/Controllers/MessagesController.cs
  samples/AlarmBot-Cards/Startup.cs
  samples/AlarmBot-Cards/Topics/AddAlarmTopic.cs
  samples/AlarmBot-Cards/Topics/DefaultTopic.cs
  samples/AlarmBot-Cards/Topics/DeleteAlarmTopic.cs
  samples/AlarmBot-Cards/Topics/ShowAlarmsTopic.cs
  samples/AlarmBot/Controllers/MessagesController.cs
  samples/AlarmBot/Startup.cs
  samples/AlarmBot/Topics/AddAlarmTopic.cs
  samples/AlarmBot/Topics/DefaultTopic.cs
  samples/AlarmBot/Topics/DeleteAlarmTopic.cs
  samples/AlarmBot/Topics/ShowAlarmsTopic.cs
  samples/Microsoft.Bot.Samples.Simplified.Asp/Controllers/MessagesController.cs
  samples/Microsoft.Bot.Samples.Simplified.Asp/Startup.cs
  tests/Microsoft.Bot.Builder.Tests/State_BasicTests.cs
Labels: dcr, enhancement

#197 Removed Custom Middleware Example. Not adding value. #189
  Microsoft.Bot.Builder.sln
  samples/Microsoft.Bot.Samples.CustomMiddleware/Controllers/MessagesController.cs
  samples/Microsoft.Bot.Samples.CustomMiddleware/Microsoft.Bot.Samples.CustomMiddleware.csproj
  samples/Microsoft.Bot.Samples.CustomMiddleware/Middleware/ExampleMiddleware.cs
  samples/Microsoft.Bot.Samples.CustomMiddleware/Program.cs
  samples/Microsoft.Bot.Samples.CustomMiddleware/Startup.cs
  samples/Microsoft.Bot.Samples.CustomMiddleware/appsettings.Development.json
  samples/Microsoft.Bot.Samples.CustomMiddleware/appsettings.json
  samples/Microsoft.Bot.Samples.CustomMiddleware/readme.md
  samples/Microsoft.Bot.Samples.CustomMiddleware/wwwroot/default.html
Labels: enhancement

#196 Addresses Issue #184, which is that bracketing should work correctly
  libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs
  libraries/Microsoft.Bot.Builder.Core/Middleware/MiddlewareSet.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_BracketingTest.cs
  tests/Microsoft.Bot.Builder.Tests/Middleware_ReceiveActivityTests.cs
Labels: bug

#205 Fixes to suggested ACtions, #200
  libraries/Microsoft.Bot.Builder.Core/MessageFactory.cs
  tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs
Labels: bug

#207 Updated to latest Recognizer packages, which support NetStandard2.0
  samples/AlarmBot-Cards/AlarmBot-Cards.csproj
  samples/AlarmBot/AlarmBot.csproj
Labels: enhancement
