Repository microsoft/botbuilder-dotnet, pull requests merged in 2018-07, with the labels that each got.

#709 Draft document describing our open-source engagement policies
  specs/BotBuilderOpenSourcePlans.md
Labels: dcr

#732 Finish addressing all tractable SAxxxx compiler warnings.
  libraries/Microsoft.Bot.Builder/IRecognizer.cs
  libraries/Microsoft.Bot.Builder/IStorage.cs
  libraries/Microsoft.Bot.Builder/ITranscriptStore.cs
  libraries/Microsoft.Bot.Builder/RecognizerResult.cs
  libraries/Microsoft.Bot.Builder/Transcript.cs
  libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs
  libraries/Microsoft.Bot.Builder/TurnContext.cs
Labels: docs

#737 Fix various doc XML issues and content.
  libraries/Microsoft.Bot.Builder/IBot.cs
  libraries/Microsoft.Bot.Builder/IMiddleware.cs
  libraries/Microsoft.Bot.Builder/ITurnContextExtensions.cs
  libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs
  libraries/Microsoft.Bot.Schema/ActivityEx.cs
  libraries/Microsoft.Bot.Schema/IActivity.cs
Labels: docs

#738 [Do Not Merge] State Management Port from JS Codebase
  libraries/Microsoft.Bot.Builder/FrameRoot.cs
  libraries/Microsoft.Bot.Builder/FrameScope.cs
  libraries/Microsoft.Bot.Builder/IFrame.cs
  libraries/Microsoft.Bot.Builder/IFrameDefinition.cs
  libraries/Microsoft.Bot.Builder/IReadOnlySlot.cs
  libraries/Microsoft.Bot.Builder/IReadWriteSlot.cs
  libraries/Microsoft.Bot.Builder/ISlotDefinition.cs
  libraries/Microsoft.Bot.Builder/Slot.cs
  libraries/Microsoft.Bot.Builder/SlotHistoryPolicy.cs
  libraries/Microsoft.Bot.Builder/SlotHistoryValue.cs
Labels: state-management, wip

#739 Update Properties property documentation.
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Builder/RecognizerResult.cs
  libraries/Microsoft.Bot.Schema/ActivityEx.cs
  libraries/Microsoft.Bot.Schema/AttachmentEx.cs
  libraries/Microsoft.Bot.Schema/ChannelAccountEx.cs
  libraries/Microsoft.Bot.Schema/ConversationAccountEx.cs
  libraries/Microsoft.Bot.Schema/EntityEx.cs
Labels: docs

#748 Address some of the missing doc XML, make some edits to existing doc XML
  libraries/Microsoft.Bot.Builder.Ai.QnA/Microsoft.Bot.Builder.Ai.QnA.csproj
  libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMaker.cs
  libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMakerEndpoint.cs
  libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMakerOptions.cs
  libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMakerTraceInfo.cs
  libraries/Microsoft.Bot.Builder.Ai.QnA/QueryResult.cs
  libraries/Microsoft.Bot.Builder.Ai.QnA/QueryResults.cs
  libraries/Microsoft.Bot.Builder.Ai.Translation/LocaleConverterMiddleware.cs
  libraries/Microsoft.Bot.Builder.Ai.Translation/TranslationMiddleware.cs
  libraries/Microsoft.Bot.Builder.Ai.Translation/Translator.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs
  libraries/Microsoft.Bot.Builder/IBot.cs
  libraries/Microsoft.Bot.Builder/IMiddleware.cs
  libraries/Microsoft.Bot.Builder/IStorage.cs
  libraries/Microsoft.Bot.Builder/MemoryStorage.cs
  libraries/Microsoft.Bot.Builder/RecognizerResultExtensions.cs
  libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs
  libraries/Microsoft.Bot.Builder/TurnContext.cs
  libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs
  libraries/Microsoft.Bot.Schema/ActivityTypesEx.cs
Labels: docs

#645 A Proposal for more robust User Agents in the Bot Framework
  doc/UserAgents.md
Labels: dcr, discussion

#756 Add more missing doc XML elements.
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/BuiltIn.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/LuisService.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/Resolution.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Generator/DateTimeSpec.cs
  libraries/Microsoft.Bot.Builder/BotState.cs
  libraries/Microsoft.Bot.Builder/IMiddleware.cs
  libraries/Microsoft.Bot.Builder/StateSettings.cs
  libraries/Microsoft.Bot.Builder/TurnContextServiceCollection.cs
Labels: docs

#763 Fix some doc XML warnings...
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/ILuisOptions.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/LuisModelAttribute.cs
  libraries/Microsoft.Bot.Builder.Ai.LUIS/Client/LuisRequest.cs
Labels: docs

#801 Remove proactive endpoint from integrations
  libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs
  libraries/Microsoft.Bot.Builder/Integration/BotFrameworkPaths.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotProactiveMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkConfigurationBuilder.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotProactiveMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/ApplicationBuilderExtensionsTests.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/HttpConfigurationExtensionsTests.cs
Labels: integration, proactive
