Repository microsoft/botbuilder-dotnet, pull requests merged in 2018-03, with the labels that each got.

#192 Expose bot AAD App details
  Microsoft.Bot.Builder.sln
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Builder/BotFrameworkBotContext.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
  samples/Microsoft.Bot.Samples.Ai.QnA/Controllers/MessagesController.cs
  tests/Microsoft.Bot.Connector.Tests/JwtTokenValidationTests.cs
Labels: enhancement

#235 Build Warning Cleanup around async methods in Release
  samples/AlarmBot-Cards/AlarmBot-Cards.csproj
  samples/AlarmBot/AlarmBot.csproj
  tests/Microsoft.Bot.Builder.Prompts.Tests/Microsoft.Bot.Builder.Prompts.Tests.csproj
  tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
Labels: enhancement

#284 Support IMessageActivity on the Context Send methods. This allows the MessageFactory to easily send.
  libraries/Microsoft.Bot.Builder.Core/BotContext.cs
  libraries/Microsoft.Bot.Builder.Core/BotContextWrapper.cs
  libraries/Microsoft.Bot.Builder.Core/IBotContext.cs
  tests/Microsoft.Bot.Builder.Core.Tests/BotContextTests.cs
Labels: enhancement

#308 Updated to latest Recognizers.Text Nuget packages
  libraries/Microsoft.Bot.Builder.Prompts/AgePrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/CurrencyPrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/DimensionPrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/Microsoft.Bot.Builder.Prompts.csproj
  libraries/Microsoft.Bot.Builder.Prompts/NumberPrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/OrdinalPrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/PercentagePrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/PhonePrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/RangePrompt.cs
  libraries/Microsoft.Bot.Builder.Prompts/TemperaturePrompt.cs
  samples/AlarmBot-Cards/AlarmBot-Cards.csproj
  samples/AlarmBot-Cards/DateTimeRecognizerExtensions.cs
  samples/AlarmBot/AlarmBot.csproj
  samples/AlarmBot/Models/AlarmBotContext.cs
  tests/Microsoft.Bot.Builder.Prompts.Tests/Microsoft.Bot.Builder.Prompts.Tests.csproj
  tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj
Labels: enhancement

#319 Fixes to BotFrameworkAdapter for Proactive Messaging
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
Labels: bug

#327 Downgrade the BotBuilder Test project to .Net 4.6.1
  tests/Microsoft.Bot.Builder.Classic.Tests/Microsoft.Bot.Builder.Classic.Tests.csproj
Labels: build

#326 Improve perf of MiddlewareSet pipeline execution
  libraries/Microsoft.Bot.Builder.Core/MiddlewareSet.cs
  tests/Microsoft.Bot.Builder.Core.Tests/MiddlewareSetTests.cs
Labels: perf

#328 Removed old projects that are no longer relevant
  libraries/Microsoft.Bot.Connector.AspNetCore/BotAuthenticationExtensions.cs
  libraries/Microsoft.Bot.Connector.AspNetCore/BotAuthenticationHandler.cs
  libraries/Microsoft.Bot.Connector.AspNetCore/BotAuthenticationOptions.cs
  libraries/Microsoft.Bot.Connector.AspNetCore/Microsoft.Bot.Connector.AspNetCore.csproj
  libraries/Microsoft.Bot.Connector.AspNetCore/TrustServiceUrlAttribute.cs
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/BotController.cs
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/Controllers/MessagesController.cs
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/MessageActivityAttribute.cs
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/MessageAttribute.cs
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/Microsoft.Bot.Samples.Simplified.Asp.csproj
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/Program.cs
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/Startup.cs
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/appsettings.Development.json
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/appsettings.json
  samples/experiments/Microsoft.Bot.Samples.Simplified.Asp/wwwroot/default.html
Labels: build

#330 Wire ResourceResponses through from the Connector through the BotContext
  libraries/Microsoft.Bot.Builder.Classic/Microsoft.Bot.Builder.Classic/ConnectorEx/BotToUser.cs
  libraries/Microsoft.Bot.Builder.Core.Extensions/BatchOutput.cs
  libraries/Microsoft.Bot.Builder.Core/Adapters/ConsoleAdapter.cs
  libraries/Microsoft.Bot.Builder.Core/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs
  libraries/Microsoft.Bot.Builder.Core/BotContext.cs
  libraries/Microsoft.Bot.Builder.Core/BotContextWrapper.cs
  libraries/Microsoft.Bot.Builder.Core/IBotContext.cs
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  tests/Microsoft.Bot.Builder.Core.Extensions.Tests/BatchOutputTests.cs
  tests/Microsoft.Bot.Builder.Core.Tests/BotAdapterTests.cs
  tests/Microsoft.Bot.Builder.Core.Tests/BotContextTests.cs
  tests/Microsoft.Bot.Builder.Core.Tests/SimpleAdapter.cs
  tests/Microsoft.Bot.Builder.Core.Tests/TestMessage.cs
  tests/Microsoft.Bot.Builder.TemplateManager/TemplateManagerTests.cs
Labels: enhancement

#331 Update the Luis sample to use the latest ASP.Net Core integration.
  samples/Microsoft.Bot.Samples.Ai.Luis/Controllers/MessagesController.cs
  samples/Microsoft.Bot.Samples.Ai.Luis/LuisBot.cs
  samples/Microsoft.Bot.Samples.Ai.Luis/Microsoft.Bot.Samples.Ai.Luis.csproj
  samples/Microsoft.Bot.Samples.Ai.Luis/Startup.cs
  samples/Microsoft.Bot.Samples.Ai.Luis/readme.md
Labels: enhancement

#359 Adding reference documentation
  libraries/Microsoft.Bot.Builder.Core/IBot.cs
  libraries/Microsoft.Bot.Builder.Core/IMiddleware.cs
  libraries/Microsoft.Bot.Builder.Core/Microsoft.Bot.Builder.Core.csproj
Labels: docs

#356 Adding ClaimsIdentity and ConnectorClient to the services collection
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Builder/BotFrameworkTurnContext.cs
Labels: enhancement

#350 Adding RetryPolicy to BotFramework Adapter.
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Builder/BotFrameworkHttpStatusCodeErrorDetectionStrategy.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkOptions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkConfigurationBuilder.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkOptions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs
  samples/Microsoft.Bot.Samples.EchoBot-AspNetCore/Startup.cs
Labels: enhancement

#365 Add doc XML to Assertions and to BotAdapter
  libraries/Microsoft.Bot.Builder.Core/Assertions.cs
  libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs
Labels: docs

#362 Add documentation XML.
  libraries/Microsoft.Bot.Builder.Core/Microsoft.Bot.Builder.Core.csproj
  libraries/Microsoft.Bot.Builder.Core/TurnContext.cs
Labels: docs
