Repository microsoft/botbuilder-dotnet, pull requests merged in 2019-06, with the labels that each got.

#1790 Small refactoring
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
  libraries/Microsoft.Bot.Connector/OAuthClientConfig.cs
Labels: 4.5, Blocked

#1850 Take magic code detection out of OAuth BeginDialog
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
Labels: Parity with JS Required, Parity with Python Required

#2003 Luhan/schema update
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AdaptiveDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AttachmentInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.DateTimeInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.OAuthInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EditSteps.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.Foreach.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.ForeachPage.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.HttpRequest.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.LogStep.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/HttpRequest.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/11 - HttpRequest/HttpRequest.main.dialog
Labels: Adaptive

#2044 Adaptive event model
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/IRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/IRuleSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/PlanningContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/EventRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/IntentRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/Rule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/UnknownIntentRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/ConditionalSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/FirstSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/MostSpecificSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/RandomSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/TrueSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/SequenceContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BaseInvokeDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BeginDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/CancelAllDialogs.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/DebugBreak.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/DeleteProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EditSteps.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EmitEvent.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EndDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EndTurn.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ForEach.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ForEachPage.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/IfCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/InitProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ReplaceDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SaveEntity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SetProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SwitchCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogCommand.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogConsultation.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs/IDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/TextPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Carlos GitHub bot/GetIssue.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Carlos GitHub bot/GetUser.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Carlos GitHub bot/GithubBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/DeleteToDo.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs
Labels: Adaptive, Labs

#2056 Update schema based on the Input update
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AttachmentInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.DateTimeInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.NumberInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.OAuthInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.TextInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/baseInputSchema.json
Labels: Adaptive

#2046 Add options in BeginDialogAsync call
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
Labels: Adaptive

#2053 [LG] add support to import lg files into another file
  libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/TemplateEngineLanguageGenerator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFile.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileParser.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGImport.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBotLG.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/import.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/InvalidLGFileImportPath.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineThrowExceptionTest.cs
Labels: Adaptive

#2048 Update EditArray
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EditArray.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EditArray.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.AddItem.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.DeleteItem.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
Labels: Adaptive

#2062 cleaned up LG Resource import delegate and hooked up to resource
  libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGenerationRenderer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGeneratorManager.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/TemplateEngineLanguageGenerator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGImport.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGSource.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBotLG.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineThrowExceptionTest.cs
Labels: Adaptive

#2064 minor schema updates
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.OAuthInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.TextInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EditSteps.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.ForeachPage.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.HttpRequest.schema
Labels: Adaptive

#2063 [WIP][LG] achieve DCR #2055,Unify the interface of TemplateEngine across f…
  libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGenerationRenderer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/TemplateEngineLanguageGenerator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBotLG.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineThrowExceptionTest.cs
Labels: Adaptive

#2075 Add new Testing library to Code Coverage Metrics
  CodeCoverage.runsettings
Labels: 4.5

#2077 Update TestBot.json to match changes to schema.
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/16 - EditSteps/EditSteps.main.dialog
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.SaveEntity.schema
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Sandwich/sandwich.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.AddItem.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.DeleteItem.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.ShowItems.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
Labels: Adaptive

#2065 [LG] use absolute file path as dictionary key
  libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LanguageGeneratorManager.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGResource.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/import.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/InvalidLGFileImportPath.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Labels: Adaptive

#2047 [Expression] Adding R2 Functions for datetime, uri Parsing, object manipulation
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs
  libraries/Microsoft.Bot.Builder.Expressions/Microsoft.Bot.Builder.Expressions.csproj
  libraries/Microsoft.Bot.Builder.Expressions/TimeZoneConverter.cs
  libraries/Microsoft.Bot.Builder.Expressions/WindowsIanaMapping
  tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#2084 Creates unit tests for TestBot
  Microsoft.Bot.Builder.sln
  libraries/Microsoft.Bot.Builder.Testing/DialogTestClient.cs
  libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
  tests/Microsoft.Bot.Builder.TestBot.Tests/Bots/DialogAndWelcomeBotTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Bots/DialogBotTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Controllers/BotControllerTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/BookingDialogTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/CancelAndHelpDialogTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/DateResolverDialogTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/GetBookingDetailsDialogTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/MainDialogTestFlowTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/MainDialogTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/BookingDialogTestCase.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/BookingDialogTestsDataGenerator.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/DateResolverDialogTestCase.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/DateResolverDialogTestsDataGenerator.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/GetBookingDetailsDialogTestCase.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/GetBookingDetailsDialogTestsDataGenerator.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/README.md
  tests/Microsoft.Bot.Builder.TestBot.Tests/Framework/BotTestBase.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Framework/README.md
  tests/Microsoft.Bot.Builder.TestBot.Tests/Framework/SimpleMockFactory.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Microsoft.Bot.Builder.TestBot.Tests.csproj
  tests/Microsoft.Bot.Builder.TestBot.Tests/appsettings.json
  tests/Microsoft.Bot.Builder.TestBot.Tests/stylecop.json
  tests/Microsoft.Bot.Builder.TestBot/Dialogs/MainDialog.cs
  tests/Microsoft.Bot.Builder.TestBot/Startup.cs
Labels: 4.5

#2087 [Adaptive] Inputs Update
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/17 - AttachmentInput/AttachmentInput.main.dialog
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/17 - AttachmentInput/showimage.lg
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/AttachmentInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/DateTimeInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AttachmentInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.NumberInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.OAuthInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.TextInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/baseInputSchema.json
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EndTurn.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/14 - RepeatDialog/RepeatDialog.main.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Labels: Adaptive

#2074 fix typos and update number -> integer where appropriate
  .vscode/settings.json
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.NumberInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/baseInputSchema.json
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.DeleteProperty.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EditArray.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EditSteps.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EmitEvent.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EndTurn.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.Foreach.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.ForeachPage.schema
Labels: Adaptive

#2083 Update TodoBot Sample
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EditArray.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/ClearToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/ShowToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/ToDoBot.main.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Labels: Adaptive

#2096 [LG] refactor analyzer
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/analyzer.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/lgTemplate.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Labels: Adaptive

#2092 Adaptive: Property property consistency and constructor alignment
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BaseInvokeDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BeginDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/DeleteProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EmitEvent.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EndDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/HttpRequest.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/InitProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SetProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
Labels: Adaptive

#2054 Support regular expression in expression
  Microsoft.Bot.Builder.sln
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  libraries/Microsoft.Bot.Builder.Expressions/CommonRegex.cs
  libraries/Microsoft.Bot.Builder.Expressions/CommonRegex.g4
  libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs
  libraries/Microsoft.Bot.Builder.Expressions/LRUCache.cs
  libraries/Microsoft.Bot.Builder.Expressions/Microsoft.Bot.Builder.Expressions.csproj
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4
  tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/LRUCacheTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/Regex.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateEngineTest.cs
Labels: Adaptive

#2134 SwitchCondition: support numeric and boolean types, and do not require quotes for string literals
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SwitchCondition.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/03 - IfCondition/SwitchCondition.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/ShowEmail/DisplayEmailList.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Labels: Adaptive

#2129 Memory storage: allow writing null value changes
  libraries/Microsoft.Bot.Builder/MemoryStorage.cs
Labels: Adaptive

#2142 Add @@ as an alias for a full entity.
  libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4
  libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1512 [StyleCop] Treat Warnings as Errors
  BotBuilder-DotNet.ruleset
  Directory.Build.props
  LICENSE
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisUtil.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj
  libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.ruleset
  libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj
  libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.ruleset
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs
  libraries/Microsoft.Bot.Builder.ApplicationInsights/BotTelemetryClient.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.ruleset
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/Find.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
  libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.ruleset
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/AttachmentPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/TextPrompt.cs
  libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj
  libraries/Microsoft.Bot.Builder/BotBuilder.ruleset
  libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
  libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs
  libraries/Microsoft.Bot.Connector/Channels.cs
  libraries/Microsoft.Bot.Schema/Activity.cs
  libraries/Microsoft.Bot.Schema/ActivityEx.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.ruleset
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.ruleset
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.ruleset
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.ruleset
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ComponentDialogTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/BookingDialogTestsDataGenerator.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Dialogs/TestData/DateResolverDialogTestsDataGenerator.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Framework/BotTestBase.cs
  tests/Microsoft.Bot.Builder.TestBot.WebApi/Dialogs/DateResolverDialog.cs
  tests/Microsoft.Bot.Builder.Tests/StorageBaseTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsRetrieverTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/EndorsementsValidatorTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/FaultyClass.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/MicrosoftGovernmentAppCredentialsTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/RetryParamsTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/RetryTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/TestConfigurationRetriever.cs
Labels: 4.5

#2127 Fix numerous dialog state binding issues
  Directory.Build.props
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/ActivityRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/EventRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/IntentRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/Rule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AdaptiveDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EditArray.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/ConditionalSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BaseInvokeDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BeginDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/DeleteProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EditArray.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EmitEvent.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EndDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EndTurn.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ForEach.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ForEachPage.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/HttpRequest.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/IfCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/InitProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ReplaceDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SetProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SwitchCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
  libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4
  libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  libraries/Microsoft.Bot.Builder.Expressions/Expression.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/GetMethodExtensions.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplate.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/BugRepo/AskForName.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/BugRepo/BugRepo.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DialogContextStateTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SelectorTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive
