Repository microsoft/botbuilder-dotnet, pull requests merged in 2019-04, with the labels that each got.

#1587 Prompts: Restore original prompts and lean on Inputdialogs for declar…
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/AttachmentPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/TextPrompt.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/DateTimePromptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/TextPromptTests.cs
Labels: Labs

#1593 Fix Ref By $copy
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resolvers/IdRefResolver.cs
Labels: Labs

#1606 Adds ChoiceStyle propery to PromptOptions so the developer can overr…
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
Labels: Parity with JS Required

#1566 Allow `LuisRecognizer` to handle textless messages
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs
Labels: Parity with JS Required

#1631 Language generation docs
  doc/Language Generation/api-reference.md
  doc/Language Generation/lg-file-format.md
  doc/Language Generation/readme.md
Labels: Adaptive, Labs

#1628 Common expression language docs
  doc/CommonExpressionLanguage/api-reference.md
  doc/CommonExpressionLanguage/prebuilt-functions.md
  doc/CommonExpressionLanguage/readme.md
Labels: Adaptive, Labs

#1594 Add ChoiceInput
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 10 - ChoiceInput/ChoiceInput.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 12 - GithubIssueBot/show.lg
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Labels: Adaptive, Labs

#1626 [nodejs parity] Allow LUIS endpoint to be null or empty
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisApplicationTests.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs
Labels: 4.4, Parity with JS Required

#1645 fix debug adapter protocol encoding
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugTransport.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Protocol.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/.vscode/launch.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/CHANGELOG.md
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/LICENSE
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/README.md
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/icon.png
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/language-configuration.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package-lock.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/syntaxes/JSON.tmLanguage.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/vscode-dialog-debugger-0.0.2.vsix
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/.vscode/launch.json
Labels: Adaptive

#1647 Add a custom CSharp step to test bot
  samples/Microsoft.Bot.Builder.TestBot.Json/CustomSteps/CSharpStep.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/CustomSteps/JavascriptStep.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/CustomSteps/Testbot.CSharpStep.schema
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/13 - CustomStep/CustomStep.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/13 - CustomStep/catyears.csx
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/13 - CustomStep/dogyears.js
  samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
Labels: Adaptive

#1651 Johtaylo/issue1257
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/PromptValidatorContextTests.cs
  tests/Microsoft.Bot.Builder.TestBot/Dialogs/UserProfileDialog.cs
  tests/Microsoft.Bot.Builder.TestBot/UserProfile.cs
Labels: 4.4, Parity with JS Required

#1655 Add IRuleSeclector
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/Microsoft.Bot.Builder.AI.TriggerTrees.csproj
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/Trigger.cs
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/TriggerTree.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/IRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/IRuleSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/Rule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AdaptiveDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Microsoft.IRuleSelector.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Rules/Microsoft.Rule.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Selectors/Microsoft.ConditionalSelector.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Selectors/Microsoft.FirstSelector.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Selectors/Microsoft.MostSpecificSelector.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Selectors/Microsoft.RandomSelector.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Selectors/Microsoft.TrueSelector.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/ConditionalSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/FirstSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/MostSpecificSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/RandomSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/TrueSelector.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs
  tests/Microsoft.Bot.Builder.AI.TriggerTrees.Tests/Microsoft.Bot.Builder.AI.TriggerTrees.Tests.csproj
  tests/Microsoft.Bot.Builder.AI.TriggerTrees.Tests/Tests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SelectorTests.cs
Labels: Adaptive

#1657 Fix ToDoLuisBot Sample
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EditArray.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/InitProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.AddItem.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.DeleteItem.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.ShowItems.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.lg
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.lgbad
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
Labels: Adaptive

#1658 [WIP]LG features
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs
  libraries/Microsoft.Bot.Builder.Expressions/Extensions.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1659 Enrich email obi bot
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Loaders/OauthPromptLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/BotBuilderTestBot.bot
  samples/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Controller/ClearForwardData.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Controller/ClearReplyData.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Controller/ClearUserData.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Controller/GetDisplayEmails.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Controller/NextPage.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/EmailBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/FindContact/FindContact.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/ForwardEmail/ForwardEmail.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/ReplyEmail/ReplyEmail.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/SendEmail/SendEmail.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/Shared/ChooseEmail.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/Shared/shared.lg
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/ShowEmail/DisplayEmailList.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/ShowEmail/ShowEmail.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Dialogs/ShowEmail/showEmail.lg
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Service/MSGraph/ForwardEmails.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Service/MSGraph/GetContact.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Service/MSGraph/GetEmails.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Service/MSGraph/ReplyEmails.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/EmailBot/Service/MSGraph/SendEmails.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/GetListType.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/ClearToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/ShowToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/ToDoBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/todo.lg
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/VARootDialog/VARootDialog.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
Labels: Adaptive

#1672 debug adapter support for "set variable" and "evaluate on hover"
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Coercion.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Model.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Policy.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Protocol.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/SourceMap.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
Labels: Adaptive

#1675 Expression: restruct test and add more tests
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1680 Expression: Add more bad expression tests
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1683 updates to BOM
  doc/BUILD 2019 BOM/AdaptiveDialogAndPromptWrappers.md
Labels: Adaptive

#1705 Change ResourceExplorer to allow ignoring of folders
  libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.LuisRecognizer.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuisBot/ToDoLuisBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/appsettings.json
  samples/Microsoft.Bot.Builder.TestBot.Json/luconfig.json
  samples/Microsoft.Bot.Builder.TestBot.Json/models/tomlm/westus/ToDoLuis.en-us.lu.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/models/tomlm/westus/ToDoLuis.lu.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceExplorerTests.cs
Labels: Adaptive, Labs

#1684 Add Calendar Bot for OBI
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/DateTimeInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/HttpRequest.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/12 - GithubIssueBot/show.lg
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Controller/CalendarClearUserData.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Controller/CalendarNextPage.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Controller/GetDisplayMeetings.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Controller/GetNewEndDateTime.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/AcceptMeeting/AcceptMeeting.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/CalendarBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/CreateMeeting/CreateMeeting.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/DeclineMeeting/DeclineMeeting.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/FindContact/CalendarFindContact.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/FindContact/CalendarFindSingleContact.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/ShowMeeting/ShowMeeting.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/UpdateMeeting/UpdateMeeting.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Dialog/calendarBot.lg
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Service/MSGraph/AcceptMeetingService.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Service/MSGraph/CreateMeetingService.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Service/MSGraph/DeclineMeetingService.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Service/MSGraph/GetContactService.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Service/MSGraph/GetMeetingsService.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/CalendarBot/Service/MSGraph/UpdateMeetingService.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/todo.lg
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/VARootDialog/VARootDialog.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBotLG.cs
Labels: Adaptive

#1681 Expression: Add string index support in access element function
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1707 Fix some of the samples
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/TextInput.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/09 - EndDialog/EndDialog.TellJoke.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/09 - EndDialog/EndDialog.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/12 - GithubIssueBot/show.lg
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/GetListType.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/ClearToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/ShowToDos.dialog
Labels: Adaptive

#1715 Switch back to IResource model for parity with javascript
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeTypeLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resolvers/IdRefResolver.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FileResource.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/IResource.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/IResourceProvider.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/LGLanguageGenerator.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceExplorerTests.cs
Labels: Adaptive

#1714 updates based on standup 4/16
  doc/BUILD 2019 BOM/AdaptiveDialogAndPromptWrappers.md
Labels: Adaptive

#1708 InputWrapper: If no property is provided we simply don't bind to memory but let the prompt go through.
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/TextInput.WithoutProperty.main.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Labels: Adaptive, Labs

#1706 Expression: Support JToken
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1716 Expression: Add +- operators and re-discuss the number of parameters
  libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4
  libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1720 Chrimc/roles
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.AdaptiveDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.FloatInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.IntegerInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.NumberInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.TextInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/baseSchema.json
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Rules/Microsoft.EventRule.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Rules/Microsoft.IntentRule.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Rules/Microsoft.Rule.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Rules/Microsoft.UnknownIntentRule.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Selectors/Microsoft.ConditionalSelector.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.BeginDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.CancelAllDialogs.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.DeleteProperty.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EditArray.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EmitEvent.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EndDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EndTurn.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.HttpRequest.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.IfCondition.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.InitProperty.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.LogStep.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.ReplaceDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.SaveEntity.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.SendActivity.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.SetProperty.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.SwitchCondition.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.TraceActivity.schema
  libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
  libraries/Microsoft.Bot.Builder.Dialogs/Schemas/Microsoft.IActivityTemplate.schema
  libraries/Microsoft.Bot.Builder.Dialogs/Schemas/Microsoft.IExpression.schema
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
Labels: Adaptive

#1717 fix Inputs Bugs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/NumberInput.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/TextInput.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoBot/AddToDo.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Labels: Adaptive

#1722 move data into turn state
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/PlanningContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/EventRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/IntentRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/UnknownIntentRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/LogStep.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SaveEntity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
  libraries/Microsoft.Bot.Builder.Dialogs/LowercaseCasingStrategy.cs
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/BotExplorer.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DialogContextStateTests.cs
Labels: Adaptive

#1729 Misc schema/samples/unit tests cleanup
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.RepeatDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogCommand.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/NumberInput.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/14 - RepeatDialog/RepeatDialog.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/15 - TraceAndLog/TraceAndLog.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1719 implement "launch bot" debug configuration
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugTransport.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Protocol.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/.gitignore
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/.vscode/launch.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/.vscode/settings.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/.vscode/tasks.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package-lock.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/src/ts/extension.ts
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/src/ts/tsconfig.json
  samples/Microsoft.Bot.Builder.TestBot.Json/.vscode/launch.json
Labels: Adaptive

#1727 Fix Prompts breaking changes
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/FloatPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/IMatchPromptOptions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/IRangePromptOptions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/IntegerPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
Labels: Adaptive

#1730 IApplicationLifetime.StopApplication graceful exit
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Coercion.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Debugging/DebugSupport.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Debugging/Source.cs
  libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
Labels: Adaptive

#1732 IApplicationLifetime.StopApplication graceful exit
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/Rule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Coercion.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/SourceMap.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/src/ts/extension.ts
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeTypeLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resolvers/IdRefResolver.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Debugging/DebugSupport.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Debugging/Source.cs
  libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/.vscode/launch.json
  samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
Labels: Adaptive

#1733 Chrimc/expressions
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/Clause.cs
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/Node.cs
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/Trigger.cs
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/TriggerTree.cs
  libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  libraries/Microsoft.Bot.Builder.Expressions/Constant.cs
  libraries/Microsoft.Bot.Builder.Expressions/Expression.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExpressionEvaluator.cs
  libraries/Microsoft.Bot.Builder.Expressions/Extensions.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExtensionsRewriters.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/GetMethodExtensions.cs
  tests/Microsoft.Bot.Builder.AI.TriggerTrees.Tests/Generator.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/RewriteTests.cs
Labels: Adaptive

#1734 Backwards compat: do not rely on options to maintain internal binding state
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BaseInvokeDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialogBase.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs/IDialog.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/14 - RepeatDialog/RepeatDialog.main.dialog
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/SelectorTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Labels: Adaptive

#1743 update vsix
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/.gitignore
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/README.md
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package-lock.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package.json
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/src/extension.ts
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/tsconfig.json
  samples/Microsoft.Bot.Builder.TestBot.Json/.vscode/launch.json
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
Labels: Adaptive

#1744 switch to dotnet standard version of nugetpackage library
  libraries/Microsoft.Bot.Builder.Dialogs.Composition/Microsoft.Bot.Builder.Dialogs.Composition.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Plugins/FileDependencyInfo.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Plugins/IPlugin.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Plugins/NuGetDependencyInfo.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Plugins/NuGetPlugin.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
Labels: Adaptive

#1747 Backward compat fixes and improvements
  libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialogBase.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogCommand.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogInstance.cs
Labels: Adaptive

#1746 allow additional properties for emit event value
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Rules/Microsoft.IntentRule.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.EmitEvent.schema
Labels: Adaptive

#1749 cleanup debug
  Directory.Build.props
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/vscode-dialog-debugger/package.json
  libraries/Microsoft.Bot.Builder/Integration/BotFrameworkOptions.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/.vscode/launch.json
  samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
Labels: Adaptive

#1750 Main change is to make booleans be false if expression is null or er…
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/BadExpressionTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1752 cleanup startup.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggingAdapterExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeAdapterExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/LGAdapterExtensions.cs
  libraries/Microsoft.Bot.Builder/AdapterExtensions.cs
  libraries/Microsoft.Bot.Builder/BotAdapter.cs
  libraries/Microsoft.Bot.Builder/MiddlewareSet.cs
  libraries/Microsoft.Bot.Builder/RegisterClassMiddleware.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Controllers/BotController.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj
  samples/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
Labels: Adaptive

#1757 Move negation into ExpressionEvaluator
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/Trigger.cs
  libraries/Microsoft.Bot.Builder.AI.TriggerTrees/TriggerTree.cs
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  libraries/Microsoft.Bot.Builder.Expressions/Constant.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExpressionEvaluator.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExtensionsRewriters.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/RewriteTests.cs
Labels: Adaptive

#1753 LG & Expression: Add StyleCop Check
  libraries/Microsoft.Bot.Builder.Expressions.Parser/ExpressionEngine.cs
  libraries/Microsoft.Bot.Builder.Expressions.Parser/Microsoft.Bot.Builder.Expressions.Parser.csproj
  libraries/Microsoft.Bot.Builder.Expressions.Parser/Microsoft.Bot.Builder.Expressions.Parser.ruleset
  libraries/Microsoft.Bot.Builder.Expressions/Constant.cs
  libraries/Microsoft.Bot.Builder.Expressions/Expression.cs
  libraries/Microsoft.Bot.Builder.Expressions/ExpressionType.cs
  libraries/Microsoft.Bot.Builder.Expressions/Extensions.cs
  libraries/Microsoft.Bot.Builder.Expressions/Microsoft.Bot.Builder.Expressions.csproj
  libraries/Microsoft.Bot.Builder.Expressions/Microsoft.Bot.Builder.Expressions.ruleset
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/GetMethodExtensions.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplate.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.ruleset
  libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateEngine.cs
Labels: Adaptive

#1754 Add middleware to address transitional location of tenantId field
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs
Labels: 4.4

#1764 Made BotState CRUD operations virtual so they can be mocked for testing.
  libraries/Microsoft.Bot.Builder/BotState.cs
Labels: 4.4

#1770 Change GetValue to use TryGetValue() and throw if value is not there
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/IntentRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Rules/UnknownIntentRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EditArray.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EndDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/HttpRequest.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/InitProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/LogStep.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SaveEntity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SendActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
  libraries/Microsoft.Bot.Builder.Dialogs/ObjectExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/readme.md
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DialogContextStateTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Labels: Adaptive

#1775 remove object level this extensions
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputWrapper.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BeginDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EditArray.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/HttpRequest.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/InitProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/LogStep.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/RepeatDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/ReplaceDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SendActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeTypeLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
  libraries/Microsoft.Bot.Builder.Dialogs/ObjectExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs
  libraries/Microsoft.Bot.Builder/ObjectAssign.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/DialogContextStateTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Composition.Tests/ObjectAssignTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Labels: Adaptive

#1771 Fix bugs in selector initialization
  .vscode/tasks.json
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Sandwich/OrderSandwichApp.en-us.lu.dialog
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Sandwich/OrderSandwichApp.json
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Sandwich/OrderSandwichApp.lu
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Sandwich/OrderSandwichApp.lu.dialog
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Sandwich/notes.txt
  Samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Sandwich/sandwich.lg
  Samples/Microsoft.Bot.Builder.TestBot.Json/luis.settings.chrimc.westus.json
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/IRuleSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/ConditionalSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/FirstSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/MostSpecificSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/RandomSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/TrueSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Schemas/Microsoft.IRecognizer.schema
  libraries/Microsoft.Bot.Builder.Expressions/ExtensionsRewriters.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/RootDialog/RootDialog.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Sandwich/sandwich.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
  samples/Microsoft.Bot.Builder.TestBot.Json/luconfig.json
  samples/Microsoft.Bot.Builder.TestBot.Json/wwwroot/index.html
Labels: Adaptive

#1784 consolidate number prompts into NumberInput
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/FloatInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/IntegerInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.FloatInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.IntegerInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.NumberInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.TextInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/04 - TextInput/NumberInput.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/13 - CustomStep/CustomStep.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
Labels: Adaptive

#1793 SaveEntity forces plan.nextStep to restart
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/BaseInvokeDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SaveEntity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SetProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SwitchCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Program.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs
Labels: Adaptive

#1796 Cancellation: Temporary fix to only continue recursion when parent exists
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
Labels: Adaptive

#1797 misc traceactivity cleanup
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Steps/Microsoft.TraceActivity.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/TraceActivity.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/StepsTests.cs
Labels: Adaptive

#1772 LG: fix lexer error
  Changes.md
  libraries/Microsoft.Bot.Builder.Expressions.Parser/Expression.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4
Labels: Adaptive

#1822 Lg: Bug fix: LG parser doesn't allow white space between IF and :
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileParser.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/BasicList.lg
Labels: Adaptive

#1827 Input controls are missing debug annotations for debugging code dialogs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/DateTimeInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/NumberInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/CodeStep.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/DebugBreak.cs
Labels: Adaptive

#1832 Expression: Add month and year to SubtractFromTime function
  libraries/Microsoft.Bot.Builder.Expressions/BuiltInFunctions.cs
  tests/Microsoft.Bot.Builder.Expressions.Tests/ExpressionEngineTests.cs
Labels: Adaptive

#1831 default logger should have better name
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugTransport.cs
Labels: Adaptive
