Repository microsoft/botbuilder-dotnet, pull requests merged in 2019-03, with the labels that each got.

#1404 Dialog.ContinueDialogAsync returns by default cancellation token as a result
  libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs
Labels: Bug

#1431 gov fix for adapter
  libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
  libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
  libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests.csproj
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi.Tests/packages.config
Labels: 4.3, P0

#1481 Disable the "Live" token refresh tests
  tests/Microsoft.Bot.Connector.Tests/GetTokenRefreshTests.cs
Labels: P0

#1402 Application Insights config from appsettings.json
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs
  tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj
  tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/ServiceResolutionTests.cs
  tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/StartupAppSettingsOnly.cs
  tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/appsettings.json.default
  tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/appsettings.json.invalid_instrumentation_key
Labels: Blocked

#1462 Add List Management && ToDo Sample Bot
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/NugetResourceProvider.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/PlanningContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Recognizers/RegexRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Rules/EventRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Rules/UtteranceRecognizeRule.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/ChangeList.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/ClearProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/SaveEntity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/SendList.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContextState.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/ClearToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/ShowToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoLuisBot/ToDoLuisBot.AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoLuisBot/ToDoLuisBot.ClearToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoLuisBot/ToDoLuisBot.DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoLuisBot/ToDoLuisBot.ShowToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoLuisBot/main.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Rules.Tests/RuleDialogTests.cs
Labels: Labs

#1554 Language Rearranging
  libraries/Microsoft.Bot.Builder.AI.LanguageGeneration/LGLanguageGenerator.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Microsoft.Bot.Builder.Dialogs.Rules.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Recognizers/MultiLanguageRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Schemas/Recognizers/Microsoft.MultiLanguageRecognizers.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Schemas/Recognizers/Microsoft.RegexRecognizer.schema
  libraries/Microsoft.Bot.Builder.Dialogs/ILanguagePolicy.cs
  libraries/Microsoft.Bot.Builder.Dialogs/LanguagePolicy.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
  libraries/Microsoft.Bot.Builder.Dialogs/Schemas/Microsoft.ILanguagePolicy.schema
  libraries/Microsoft.Bot.Builder.Dialogs/Schemas/Policies/Microsoft.LanguagePolicy.schema
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
  tests/Microsoft.Bot.Builder.Dialogs.Rules.Tests/RecognizerTests.cs
Labels: Labs

#1527 Retain binary compatibility for LUIS recognizer
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisPredictionOptions.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs
  tests/Microsoft.Bot.Builder.TestBot/LuisHelper.cs
Labels: P0

#1552 update todo sample
  libraries/Microsoft.Bot.Builder.Dialogs/TextMessageActivityGenerator.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/ClearToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/ShowToDos.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/ToDoBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/todo.lg
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
Labels: Labs

#1549 HttpRequest step bug fix
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/HttpRequest.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - 12 GithubIssueBot/GithubIssueBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - 12 GithubIssueBot/show.lg
Labels: Labs

#1567 Declarative steps parity and minor adjustments
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resolvers/IdRefResolver.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/PlanningContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/ClearProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/CodeStep.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/EmitEvent.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/IfProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/OnCatch.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/RepeatDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Steps/SetProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  tests/Microsoft.Bot.Builder.Dialogs.Rules.Tests/AdaptiveDialogTests.cs
Labels: Labs

#1569 Input Wrappers: first pass
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Schemas/Microsoft.FloatInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Schemas/Microsoft.IntegerInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Schemas/Microsoft.TextInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/Factory.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Input/BoolInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Input/FloatInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Input/InputWrapper.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Input/IntegerInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Input/NumberInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Rules/Input/TextInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/FloatPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/IntegerPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/TextPrompt.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Carlos GitHub bot/GetIssue.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Carlos GitHub bot/GetUser.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Carlos GitHub bot/GithubBot.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoBot/DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoLuisBot/ToDoLuisBot.AddToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning - ToDoLuisBot/ToDoLuisBot.DeleteToDo.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 0 - TextPrompt/SimplePrompt.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 3 - IfProperty/IfProperty.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 4 - TextPrompt/TextPrompt.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 5 - WelcomeRule/WelcomeRule.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 6 - DoSteps/DoSteps.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 7 - CallDialog/CallDialog.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 8 - ExternalLanguage/ExternalLanguage.Greeting.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/Samples/Planning 9 - CancelDialog/CancelDialog.main.dialog
  samples/Microsoft.Bot.Builder.TestBot.Json/app.schema
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Rules.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Rules.Tests/StepsTests.cs
Labels: Labs
