Repository microsoft/botbuilder-dotnet, pull requests merged in 2019-02, with the labels that each got.

#1370 Apply limits to the CosmosDB Key Length
  libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDBKeyEscapeTests.cs
Labels: Blocked, Parity with JS Required

#1373 Fixing bug around request buffering
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs
  tests/Microsoft.Bot.Builder.TestBot/Startup.cs
Labels: Integration, aspnet

#1380 remove events we don't want right now
  libraries/Microsoft.Bot.Builder/ActivityHandler.cs
  tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
Labels: Parity with JS Required

#1378 additional constructor that takes raw LUIS endpoint
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisApplicationTests.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisRecognizerTests.cs
Labels: Blocked, Parity with JS Required

#1397 Fix various doc XML issues
  libraries/Microsoft.Bot.Builder/ActivityHandler.cs
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
Labels: Docs
