Repository microsoft/botbuilder-dotnet, pull requests merged in 2020-07, with the labels that each got.

#4202 Add Teams Channel Restored event
  libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
Labels: no parity

#4183 Porting Adaptive Templates to Xunit
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Startup.cs
Labels: BF Code Quality, R10, changes required, no parity

#4147 Add missing code docs for the AI libraries (LUIS / QnA)
  libraries/Microsoft.Bot.Builder.AI.LUIS/Generator/GeographyV2.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/Generator/OrdinalV2.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/ITelemetryRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisAdaptiveRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisApplication.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisExtensions.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptions.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV2.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisTelemetryConstants.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj
  libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisApplication.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/ITelemetryQnAMaker.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/FeedbackRecords.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/Metadata.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAMakerTraceInfo.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerEndpoint.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/BindToActivity.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnATelemetryConstants.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/TrainUtils.cs
Labels: no parity

#4171 [Engineering] Update codeowners
  .github/CODEOWNERS
Labels: BF Agility, changes required

#4137 Add missing code docs to integration libraries
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ApplicationBuilderExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandlerBase.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationChannelProvider.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationCredentialProvider.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Skills/SkillHttpClient.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkConfigurationBuilder.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkConfigurationBuilderExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandlerBase.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/ConfigurationChannelProvider.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/ConfigurationCredentialProvider.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/HttpConfigurationExtensions.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
Labels: no parity

#4075 [Expression] Add merge prebuilt function for merging JSON object
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/ExpressionType.cs
  tests/AdaptiveExpressions.Tests/BadExpressionTests.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: Blocked

#4215 Remove preview tag from adapters
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj
Labels: no parity

#3936 Fix formatNumber unit test
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: changes required

#4201 add Microsoft.Test.SettingsPropertiesMock
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/AdaptiveTestingComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/MockSettingsMiddleware.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertiesMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertyAssignment.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertyMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Schemas/Microsoft.Test.IPropertyMock.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Schemas/Microsoft.Test.PropertiesMock.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Schemas/Microsoft.Test.Script.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/TestScriptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/PropertyMock/properties.mock.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/PropertyMock/propertiesbase.mock.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_PropertyMock.test.dialog
  tests/tests.schema
Labels: Adaptive

#4229 fix for OnUnknownIntent title.
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnUnknownIntent.schema
Labels: Adaptive, R10

#4232 Updates to SkillHttpClient and BotFrameworkClient
  libraries/Microsoft.Bot.Builder/InvokeResponse{T}.cs
  libraries/Microsoft.Bot.Builder/Skills/BotFrameworkClient.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Skills/SkillHttpClient.cs
  tests/Microsoft.Bot.Builder.Tests/InvokeResponseOfTTests.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpClientTests.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Skills/SkillHttpClientTests.cs
Labels: no parity

#4210 Refine ActivityFactory
  libraries/Microsoft.Bot.Builder/ActivityFactory.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/DignosticStructuredLG.lg
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/lg/NormalStructuredLG.lg
Labels: LG

#4204 Additional channel/chat lifecycle events
  libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
Labels: no parity

#4267 Add additional null checks to telemetry logger middleware.
  libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs
Labels: no parity

#4271 Add extension methods to set and get the Locale of an IActivity inter…
  libraries/Microsoft.Bot.Schema/IActivityExtensions.cs
  tests/Microsoft.Bot.Schema.Tests/IActivityExtensionsTests.cs
Labels: no parity

#4274 Added FxCop and Async analyzers to the QnAMaker project.
  libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/FeedbackRecords.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/Metadata.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAMakerTraceInfo.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAResponseContext.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/QueryResult.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/QueryResults.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/RankerTypes.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/HttpRequestUtils.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Labels: no parity

#4285 Added FxCop to Dialogs.Adaptive
  BotBuilder-DotNet.ruleset
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
  libraries/AdaptiveExpressions/AdaptiveExpressions.csproj
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/ActionChangeList.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/ActionContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScopeCommands.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/Case.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DebugBreak.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DeleteProperties.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DynamicBeginDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditActions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditArray.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachPage.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/GotoAction.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/IfCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SetProperties.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SwitchCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/TelemetryTrackEventAction.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogState.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/EntityAssignments.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/MultiLanguageGenerator.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/MultiLanguageGeneratorBase.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/Ask.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInputOptions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LGResourceLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGenerator.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGeneratorExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguagePolicy.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/Converters/DialogExpressionConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/DialogExpression.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/CrossTrainedRecognizerSet.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/EntityRecognizers/EntityRecognizerSet.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RecognizerSet.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/ValueRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/SchemaHelper.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Selectors/RandomSelector.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/TextTemplate.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Extensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnChooseIntent.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnChooseProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnIntent.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/Tokenizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Memory/DialogStateManager.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptCultureModels.cs
  libraries/Microsoft.Bot.Builder/ActivityFactory.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs
Labels: no parity

#4300 Adds FxCop to Adaptive.Testing
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestSequenceMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpResponseMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/SequenceResponseManager.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertiesMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyOneOf.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserConversationUpdate.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs
Labels: no parity

#4296 Adds FxCop to Dialogs.Declarative.
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionObserver.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Parsers/TemplateExpressionParser.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProviderExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/Resource.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
Labels: no parity

#4302 Added FxCop to Adaptive.Teams
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.csproj
Labels: no parity

#4304 Use RuntimeInformation.FrameworkDescription if TargetFrameworkAttribute.FrameworkName is null
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisDelegatingHandler.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/HttpRequestUtils.cs
  libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
Labels: no parity

#4301 Added FxCop to LanguageGenreation.
  libraries/Microsoft.Bot.Builder.LanguageGeneration/AnalyzerResult.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/EvaluationOptions.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Extensions.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj
  libraries/Microsoft.Bot.Builder.LanguageGeneration/MultiLanguageLG.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Template.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateException.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs
Labels: no parity

#4122 use MSBuildThisFileDirectory in DBP
  Directory.Build.props
Labels: changes required

#4184 Porting Adaptive Teams to Xunit
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests/ConditionalTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests/Startup.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests/TestUtils.cs
Labels: Blocked, R10, changes required, no parity

#4199 use new HttpContent each time for HttpRequestMock
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestSequenceMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpResponseMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpResponseMockContent.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/SequenceResponseManager.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/HttpRequestMock/all.mock.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_HttpRequestMock.test.dialog
  tests/tests.schema
Labels: Adaptive, changes required

#4282 Add missing XML docs to Microsoft.Bot.Builder.TemplateManager
  libraries/Microsoft.Bot.Builder.TemplateManager/DictionaryRenderer.cs
  libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj
  libraries/Microsoft.Bot.Builder.TemplateManager/TemplateManager.cs
  libraries/Microsoft.Bot.Builder.TemplateManager/TemplateOptions.cs
Labels: BF Docs, R10, changes required

#4297 Added FxCop to Dialogs.Debugging.
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/SemaphoreSlimExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ICoercion.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebugTransport.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggingBotAdapterExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Events/IEvents.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Protocol.cs
Labels: no parity

#4298 ActivityPrompt.RepromptDialogAsync call OnPromptAsync with isRetry false
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ActivityPromptTests.cs
Labels: no parity

#4306 Lower time needed to complete running tests
  FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/Microsoft.Bot.Builder.FunctionalTests.csproj
  build/yaml/botbuilder-dotnet-ci.yml
  build/yaml/ci-api-validation-steps.yml
  build/yaml/ci-build-steps.yml
  build/yaml/ci-test-steps.yml
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Microsoft.Bot.Builder.Adapters.Facebook.Tests.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/Microsoft.Bot.Builder.Adapters.Twilio.Tests.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft.Bot.Builder.Adapters.Webex.Tests.csproj
  tests/AdaptiveExpressions.Tests/AdaptiveExpressions.Tests.csproj
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj
  tests/Microsoft.Bot.Builder.AI.Luis.TestUtils/Microsoft.Bot.Builder.AI.Luis.TestUtils.csproj
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/Microsoft.Bot.Builder.AI.QnA.Tests.csproj
  tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Microsoft.Bot.Builder.AI.LuisV3.Tests.csproj
  tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj
  tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests/Microsoft.Bot.Builder.Dialogs.Debugging.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.Tests.csproj
  tests/Microsoft.Bot.Builder.Testing.Tests/Microsoft.Bot.Builder.Testing.Tests.csproj
  tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
  tests/Microsoft.Bot.Builder.Transcripts.Tests/Microsoft.Bot.Builder.Transcripts.Tests.csproj
  tests/Microsoft.Bot.Configuration.Tests/Microsoft.Bot.Configuration.Tests.csproj
  tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
  tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj
  tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj
  tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj
Labels: no parity

#4307 Make ActivityPrompt a normal class - remove abstract
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs
Labels: no parity

#4303 Add missing XML documentation to Microsoft.Bot.Schema
  libraries/Microsoft.Bot.Schema/AadResourceUrls.cs
  libraries/Microsoft.Bot.Schema/ActionTypes.cs
  libraries/Microsoft.Bot.Schema/ActivityImportance.cs
  libraries/Microsoft.Bot.Schema/ActivityTypes.cs
  libraries/Microsoft.Bot.Schema/AttachmentLayoutTypes.cs
  libraries/Microsoft.Bot.Schema/ContactRelationUpdateActionTypes.cs
  libraries/Microsoft.Bot.Schema/ContentTypes.cs
  libraries/Microsoft.Bot.Schema/DeliveryModes.cs
  libraries/Microsoft.Bot.Schema/EndOfConversationCodes.cs
  libraries/Microsoft.Bot.Schema/EntityEx.cs
  libraries/Microsoft.Bot.Schema/InputHints.cs
  libraries/Microsoft.Bot.Schema/InstallationUpdateActionTypes.cs
  libraries/Microsoft.Bot.Schema/MessageReactionTypes.cs
  libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj
  libraries/Microsoft.Bot.Schema/RoleTypes.cs
  libraries/Microsoft.Bot.Schema/SignInResource.cs
  libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionAction.cs
  libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionActionResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionAttachment.cs
  libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionQuery.cs
  libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionResult.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsPagedMembersResult.cs
  libraries/Microsoft.Bot.Schema/TextFormatTypes.cs
  libraries/Microsoft.Bot.Schema/TokenExchangeRequest.cs
  libraries/Microsoft.Bot.Schema/TokenExchangeResource.cs
  libraries/Microsoft.Bot.Schema/TokenResponse.cs
Labels: BF Docs, R10

#4299 Add missing XML documentation to Microsoft.Bot.Connector
  libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs
  libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs
  libraries/Microsoft.Bot.Connector/Authentication/AuthenticatorResult.cs
  libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/IAuthenticator.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs
  libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/Retry.cs
  libraries/Microsoft.Bot.Connector/Authentication/RetryParams.cs
  libraries/Microsoft.Bot.Connector/Authentication/SimpleChannelProvider.cs
  libraries/Microsoft.Bot.Connector/Authentication/ThrottleException.cs
  libraries/Microsoft.Bot.Connector/Authentication/TimeSpanExtensions.cs
  libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
  libraries/Microsoft.Bot.Connector/OAuthClient.cs
  libraries/Microsoft.Bot.Connector/OAuthClientConfig.cs
Labels: BF Docs, R10

#4327 Add missing XML documentation to Microsoft.Bot.Builder
  libraries/Microsoft.Bot.Builder/ActivityHandler.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs
  libraries/Microsoft.Bot.Builder/AutoSaveStateMiddleware.cs
  libraries/Microsoft.Bot.Builder/BotAdapter.cs
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Builder/BotState.cs
  libraries/Microsoft.Bot.Builder/ChannelServiceHandler.cs
  libraries/Microsoft.Bot.Builder/DelegatingTurnContext.cs
  libraries/Microsoft.Bot.Builder/FileTranscriptLogger.cs
  libraries/Microsoft.Bot.Builder/HandoffEventNames.cs
  libraries/Microsoft.Bot.Builder/IBotTelemetryClientExtensions.cs
  libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs
  libraries/Microsoft.Bot.Builder/Inspection/InspectionState.cs
  libraries/Microsoft.Bot.Builder/Inspection/InterceptionMiddleware.cs
  libraries/Microsoft.Bot.Builder/Integration/BotFrameworkPaths.cs
  libraries/Microsoft.Bot.Builder/Integration/MessageSerializerSettings.cs
  libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
  libraries/Microsoft.Bot.Builder/MiddlewareSet.cs
  libraries/Microsoft.Bot.Builder/NullBotTelemetryClient.cs
  libraries/Microsoft.Bot.Builder/OAuth/IUserTokenProvider.cs
  libraries/Microsoft.Bot.Builder/PathUtils.cs
  libraries/Microsoft.Bot.Builder/RecognizerResult.cs
  libraries/Microsoft.Bot.Builder/Skills/BotFrameworkClient.cs
  libraries/Microsoft.Bot.Builder/Skills/SkillConversationReference.cs
  libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs
  libraries/Microsoft.Bot.Builder/SkypeMentionNormalizeMiddleware.cs
  libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs
  libraries/Microsoft.Bot.Builder/Streaming/IStreamingActivityProcessor.cs
  libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
  libraries/Microsoft.Bot.Builder/Streaming/VersionInfo.cs
  libraries/Microsoft.Bot.Builder/StringUtils.cs
  libraries/Microsoft.Bot.Builder/Teams/TeamsActivityExtensions.cs
  libraries/Microsoft.Bot.Builder/TelemetryConstants.cs
  libraries/Microsoft.Bot.Builder/TelemetryLoggerConstants.cs
  libraries/Microsoft.Bot.Builder/TraceTranscriptLogger.cs
  libraries/Microsoft.Bot.Builder/TurnContext.cs
  libraries/Microsoft.Bot.Builder/TurnContextStateCollection.cs
Labels: BF Docs, R10

#4337 Added FxCop analyzers to Configuration
  libraries/Microsoft.Bot.Configuration/BotConfiguration.cs
  libraries/Microsoft.Bot.Configuration/EncryptUtilities.cs
  libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
  libraries/Microsoft.Bot.Configuration/ServiceTypes.cs
  libraries/Microsoft.Bot.Configuration/Services/AppInsightsService.cs
  libraries/Microsoft.Bot.Configuration/Services/ConnectedService.cs
  libraries/Microsoft.Bot.Configuration/Services/DispatchService.cs
  libraries/Microsoft.Bot.Configuration/Services/GenericService.cs
  libraries/Microsoft.Bot.Configuration/Services/LuisService.cs
Labels: no parity

#4289 Add missing XML documentation to Microsoft.Bot.Builder.Dialogs.Declarative.
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeType.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Loaders/DefaultLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Loaders/ICustomDeserializer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionObserver.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Parsers/TemplateExpressionParser.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FileResource.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceProvider.cs
Labels: BF Docs, R10

#4350 Temporarily suppressing XUnit warnings
  tests/Directory.Build.props
Labels: R10, no parity

#4352 Changing dialog.testing primarily internal
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/ReaderWriterLock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/ReferenceEquality.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/SemaphoreSlimExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModels/CodePoint.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModels/ICodeModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DataModelBase.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DictionaryDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/EnumerableDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ICoercion.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/JValueDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ListDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/NullDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ReadOnlyDictionaryDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ReflectionDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ScalarDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Events/Events.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/IdentifierCache.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/IdentifierFactory.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/IdentifierMutex.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/Identifier{T}.cs
  tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs
Labels: R10
