Repository microsoft/botbuilder-dotnet, pull requests merged in 2020-05, with the labels that each got.

#3845 Adds serialization fix for #3833
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
Labels: R9

#3827 OAuthInput: create parity with OAuthPrompt
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
Labels: Adaptive

#3780 Timex function for hasFullDate and hasValidHour builtin-functions
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/ExpressionType.cs
  tests/AdaptiveExpressions.Tests/BadExpressionTests.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: changes required

#3857 Adaptive: Detect and load graph cycles during type loading
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/Converters/DialogExpressionConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionObserver.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionPasses.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/IConverterObserver.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/IObservableConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_ReplaceDialogRecursive.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Json/Microsoft.Bot.Builder.TestBot.Json.csproj
  tests/Microsoft.Bot.Builder.TestBot.Json/Samples/CycleDetection/Child1.dialog
  tests/Microsoft.Bot.Builder.TestBot.Json/Samples/CycleDetection/Root.dialog
Labels: Adaptive, P1

#3869 Allow default(array) implicit assignment
  libraries/AdaptiveExpressions/ExpressionProperties/ArrayExpression.cs
  libraries/AdaptiveExpressions/ExpressionProperties/StringExpression.cs
  tests/AdaptiveExpressions.Tests/ExpressionPropertyTests.cs
Labels: P0, R9

#3866 SkillDialogUpdates for ConnectionName.
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.SkillDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Skills/AdaptiveSkillDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/BeginSkillDialogOptions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialogOptions.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs
Labels: R9, no parity

#3924 Do NOT call TeamsInfo.getMember for the bot cherry-pick from 4.9 (#3923)
  libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
Labels: no parity

#3944 [PORT]Maintain the high priority and independence of multiline
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Extensions.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileParser.g4
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/Multiline.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Labels: LG, R10

#3912 Support long/int64 in number constant
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/parser/ExpressionParser.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: R10

#3927 nuget.client package reference is obselete, replaced with nuget.packaging
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
  tests/Microsoft.Bot.Builder.TestBot.Json/Samples/DoubleReference/sub2.dialog
  tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema
  tests/tests.schema
Labels: no parity

#3964 Update Nuget.Client to resolve circular reference exception
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
Labels: BF:Patch:4.9

#3966 Fixes BadRequest message in Teams
  libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs
Labels: no parity

#3978 Auth: Tighten JWT validation of channel-issued tokens with certificate signature
  build/yaml/botbuilder-dotnet-ci-mac.yml
  libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs
Labels: BF:Patch:4.9

#3994 Add sentenceCase && titleCase builtin function
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/ExpressionType.cs
  tests/AdaptiveExpressions.Tests/BadExpressionTests.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: R10, expression

#3992 Add EOL builtin function
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/ExpressionType.cs
  tests/AdaptiveExpressions.Tests/BadExpressionTests.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: R10, expression

#3932 Make data and locale optional in multilingual LG
  libraries/Microsoft.Bot.Builder.LanguageGeneration/MultiLanguageLG.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/MultilanguageLGTest.cs
Labels: R10
