Repository microsoft/botbuilder-dotnet, pull requests merged in 2020-03, with the labels that each got.

#3470 Add new function in expression
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/ExpressionType.cs
  tests/AdaptiveExpressions.Tests/ExpressionEngineTests.cs
Labels: LG

#3474 SkillDialog updates
  FunctionalTests/Skills/DialogToDialog/DialogRootBot/DialogRootBot.csproj
  FunctionalTests/Skills/DialogToDialog/DialogRootBot/Dialogs/MainDialog.cs
  Microsoft.Bot.Builder.Skills.sln
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialogArgs.cs
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialogOptions.cs
  libraries/Microsoft.Bot.Builder.Testing/DialogTestClient.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs
  tests/Microsoft.Bot.Builder.Testing.Tests/DialogTestClientTests.cs
Labels: no parity

#3486 Fixed issue with null attachment arrays in AttachmentInput
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_AttachmentInput.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_TextInputWithInvalidPrompt - Copy.test.dialog
Labels: R8, adaptive, bug

#3487 Normalize Linux functional test variables
  build/yaml/botbuilder-dotnet-functional-test-linux.yml
Labels: no parity

#3471 API naming for Expression
  CodeCoverage.runsettings
  libraries/AdaptiveExpressions/Expression.cs
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/IComponentExpressionFunctions.cs
  libraries/AdaptiveExpressions/parser/ExpressionAntlrLexer.g4
  libraries/AdaptiveExpressions/parser/ExpressionAntlrParser.g4
  libraries/AdaptiveExpressions/parser/ExpressionParser.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/ComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFile.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGParser.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
  tests/AdaptiveExpressions.Tests/RewriteTests.cs
  tests/AdaptiveExpressions.Tests/TriggerTrees/Generator.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/Expand.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/TemplateAsFunction.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/TemplateNameWithDot.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/LGFileTest.cs
Labels: LG

#3457 Fix YAML file for functional-test-unix
  build/yaml/botbuilder-dotnet-functional-test-linux.yml
Labels: no parity

#3501 Update LG template content range
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFile.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplate.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/2.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/LGFileTest.cs
Labels: LG

#3491 Adaptive Telemetry Instrumentation
  libraries/AdaptiveExpressions/Converters/ExpressionConverter.cs
  libraries/AdaptiveExpressions/Expression.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BeginDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/RepeatDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ReplaceDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/DialogManager.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LUIS/LuisAdaptiveRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/QnAMaker/QnAMakerRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/CrossTrainedRecognizerSet.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RecognizerSet.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/ValueRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Recognizer.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/MiscTests.cs
Labels: adaptive, expression

#3494 Functional test Linux fixes
  FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/DirectLineClientTests.cs
  build/yaml/botbuilder-dotnet-functional-test-linux.yml
  build/yaml/functional-test-setup-steps.yml
Labels: no parity

#3507 Added interruptions support to SkillDialog
  FunctionalTests/Skills/DialogToDialog/DialogRootBot/Dialogs/MainDialog.cs
  FunctionalTests/Skills/DialogToDialog/DialogRootBot/Dialogs/TangentDialog.cs
  FunctionalTests/Skills/DialogToDialog/DialogSkillBot/Bots/SkillBot.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
Labels: Skills

#3508 Standardize triggers & coding across builds
  build/yaml/botbuilder-dotnet-ci-facebook-test.yml
  build/yaml/botbuilder-dotnet-ci-mac.yml
  build/yaml/botbuilder-dotnet-ci-slack-test.yml
  build/yaml/botbuilder-dotnet-ci-twilio-test.yml
  build/yaml/botbuilder-dotnet-ci-webex-test.yml
  build/yaml/botbuilder-dotnet-ci.yml
  build/yaml/botbuilder-dotnet-functional-tests-setup.yml
  build/yaml/botbuilder-dotnet-sign.yml
  build/yaml/botbuilder-dotnet-simple-build-test.yml
Labels: no parity

#3469 Add LG telemetry
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/LogAction.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/UpdateActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/QnAMaker/QnAMakerDialog2.cs
Labels: LG, P0, R8

#3511 Add triggers for Webex test build
  build/yaml/botbuilder-dotnet-ci-webex-test.yml
Labels: no parity

#3453 Add AdaptiveSkillDialog
  Microsoft.Bot.Builder.Skills.sln
  Microsoft.Bot.Builder.sln
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.SkillDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Skills/AdaptiveSkillDialog.cs
  libraries/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
  libraries/Microsoft.Bot.Builder.Skills/icon.png
  schemas/sdk.schema
  tests/Microsoft.Bot.Builder.Skills.Tests/Microsoft.Bot.Builder.Skills.Tests.csproj
  tests/Microsoft.Bot.Builder.TestBot.Json/Controllers/SkillController.cs
  tests/Microsoft.Bot.Builder.TestBot.Json/Samples/80 - AdaptiveSkillDialog/AdaptiveSkillDialog.main.dialog
  tests/Microsoft.Bot.Builder.TestBot.Json/SkillConversationIdFactory.cs
  tests/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
  tests/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
  tests/Microsoft.Bot.Builder.TestBot.Json/appsettings.json
Labels: Skills, no parity

#3514 Set up CI build to get coveralls token from key vault
  build/yaml/botbuilder-dotnet-ci.yml
  build/yaml/ci-test-steps.yml
Labels: no parity

#3522 Add Ephemeral to DeliveryModes, update comments
  libraries/Microsoft.Bot.Schema/Activity.cs
  libraries/Microsoft.Bot.Schema/DeliveryModes.cs
Labels: no parity

#3480 API naming for LG
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/ActivityChecker.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/SimpleMultiLangGenerator.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/ActivityTemplate.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/ErrorListener.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/MultiLanguageLG.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Template.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateException.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateImport.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs
  libraries/Microsoft.Bot.Builder/ActivityFactory.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityCheckerTest.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/SimpleMultiLangGeneratorTests.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/MultiLanguage/a.en.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/MultiLanguage/a.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/MultilanguageLGTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
  tests/Microsoft.Bot.Builder.TestBot.Json/TestBotLG.cs
  tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
Labels: LG, P0

#3529 Microsoft.Bot.Builder.Dialogs.Adaptive.Testing had release labels for creating nuget
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj
Labels: adaptive, no parity

#3536 Add unit test for CancelAllDialogs and fix eventName and eventValue null
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/CancelAllDialogs.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Recognizer.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_CancelAllDialogs.test.dialog
Labels: R8, adaptive, bug

#3544 Fix path resolver not working when alias in middle
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/PathResolvers/AliasPathResolver.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_SetProperty.test.dialog
Labels: R9

#3563 Dialog Debug Adapter improvements
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/Extensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/ReaderWriterLock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/ReferenceEquality.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModels/CodePoint.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/CodeModels/ICodeModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DataModelBase.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DictionaryDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/EnumerableDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ICoercion.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/IDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/JValueDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ListDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/NullDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ReadOnlyDictionaryDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ReflectionDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/ScalarDataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Events/Events.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Events/IEvents.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/Identifier.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/Identifier{T}.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Protocol.cs
Labels: R9, no parity

#3582 Debug Adapter Protocol Support for variablesReference in OutputEvent
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DataModels/DataModel.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DebuggerSourceMap.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/IIdentifier{T}.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/IdentifierCache.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Identifiers/Identifier{T}.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Debugging/IDialogDebugger.cs
Labels: R9

#3554 fix index access bug caused by Access Modifiers of C# class
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: LG, R9

#3575 [activityfactory] Improve missing type error
  libraries/Microsoft.Bot.Builder/ActivityFactory.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/ActivityFactoryTests.cs
Labels: LG, R9

#3597 Remove unnecessary restrication on memory path
  libraries/AdaptiveExpressions/Memory/SimpleObjectMemory.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: customer-reported

#3594 Add Push/Pop services to TurnContextStateCollection.
  libraries/AdaptiveExpressions/ExpressionProperties/ExpressionProperty.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/DialogExpression.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Debugging/DebugSupport.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Debugging/IDialogDebugger.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Debugging/NullDialogDebugger.cs
  libraries/Microsoft.Bot.Builder/TurnContextStateCollection.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs
  tests/Microsoft.Bot.Builder.Tests/TurnContextStateCollectionTests.cs
Labels: DCR, R9

#3580 update expression escape
  libraries/AdaptiveExpressions/Constant.cs
  libraries/AdaptiveExpressions/parser/ExpressionAntlrLexer.g4
  libraries/AdaptiveExpressions/parser/ExpressionParser.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/EscapeCharacter.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Labels: LG, R9

#3601 add title to choices and confirmChoices schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ChoiceInput.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.ConfirmInput.schema
Labels: no parity

#3618 fix Antler Parser build warnings
  libraries/AdaptiveExpressions/parser/ExpressionParser.cs
Labels: no parity

#3640 DCR: Change .dialog file string resource lookup to fallback to non-dialog files.
  libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj
  libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FileResource.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProvider.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/FolderResourceProviderExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
Labels: DCR, adaptive

#3632 [DCR] Add support for declarative custom dialogs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestingComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DynamicBeginDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/DynamicBeginDialogDeserializer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/ActivityTemplateConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LUIS/LuisComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGenerationComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/QnAMaker/QnAMakerComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/DeclarativeComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/IComponentDeclarativeTypes.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Loaders/ComponentDialogLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Types/UriTypeBinder.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionScopeTests/ActionScope_Goto.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionScopeTests/ActionScope_Goto_Nowhere.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionScopeTests/ActionScope_Goto_Parent.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_DynamicBeginDialog.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_TextInputWithInvalidPrompt - Copy.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/CustomAction.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/CustomAction.dialog.schema
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/GeneratorTests/sandwich/luis/sandwichTest.lu.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/GeneratorTests/unittests/luis/unittests.lu.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/LuisRecognizerTests/DynamicLists.test.en-us.lu.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/LuisRecognizerTests/DynamicLists.test.lu.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/LuisRecognizerTests/ExternalEntities.test.en-us.lu.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/LuisRecognizerTests/ExternalEntities.test.lu.dialog
  tests/Microsoft.Bot.Builder.TestBot.Json/Samples/ToDoLuis.lu.dialog
  tests/Microsoft.Bot.Builder.TestBot.Json/Samples/sandwich/luis/sandwich.lu.dialog
  tests/Microsoft.Bot.Builder.TestBot.Json/Startup.cs
Labels: DCR
