Repository microsoft/botbuilder-dotnet, pull requests merged in 2020-09, with the labels that each got.

#4517 Support create object with multi lines in LG
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplateLexer.g4
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/MultiLineExpr.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Labels: Area: LG

#4596 Add catch for JsonException in GetBodyContent.
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
Labels: no parity

#4557 [xUnit] Fix issues on AdaptiveExpressions.Tests
  tests/AdaptiveExpressions.Tests/ExpressionPropertyTests.cs
  tests/AdaptiveExpressions.Tests/LRUCacheTest.cs
Labels: no parity

#4597 Add catch for JsonException in GetBodyContent. (#4596)
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
Labels: no parity

#4344 fix null object reference
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/MultiLanguageRecognizer.cs
Labels: Area: Adaptive

#4535 Add version expression property to luisadapter and make options expression properties
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisAdaptivePredictionOptions.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisAdaptiveRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/Schemas/Microsoft.LuisRecognizer.schema
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs
  tests/tests.schema
Labels: R10

#4577 Update doc XML
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs
Labels: Area: Docs

#4561 [xUnit] Fix issues on Microsoft.Bot.Builder.Tests
  tests/Microsoft.Bot.Builder.Tests/EventFactoryTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerNotImplementedTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
  tests/Microsoft.Bot.Builder.Tests/TelemetryMiddlewareTests.cs
  tests/Microsoft.Bot.Builder.Tests/Transcript_MiddlewareTests.cs
  tests/Microsoft.Bot.Builder.Tests/TurnContextTests.cs
Labels: no parity

#4446 QnAMaker GenerateAnswer StrictFiltersCompoundOperationType for Metadata Join Operation
  libraries/Microsoft.Bot.Builder.AI.QnA/JoinOperator.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Schemas/Microsoft.QnAMakerDialog.schema
  libraries/Microsoft.Bot.Builder.AI.QnA/Schemas/Microsoft.QnAMakerRecognizer.schema
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerRecognizerTests.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Json/testbot.schema
  tests/tests.schema
Labels: Area: AI-QnAMaker

#4574 Make DisplayQnAResultAsync protected
  libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
Labels: changes required

#4629 Add OnInstallationUpdateActivity in adaptive trigger conditions
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnInstallationUpdateActivity.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnInstallationUpdateActivity.uischema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnInstallationUpdateActivity.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ConditionalsTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ConditionalsTests/ConditionalsTests_OnActivityTypes.test.dialog
  tests/tests.schema
  tests/tests.uischema
Labels: Area: Adaptive, P1

#4644 Revert TranscriptMiddleware to not wait on logging
  libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs
Labels: no parity

#4616 cache reference dialog into a dictionary when loading dup dialogs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_BeginDialog_With_Dup_Dialog_Ref/AdaptiveDialog_BeginDialog_With_Dup_Dialog_Ref.test.dialog
Labels: Area: Adaptive, P0

#4627 Make Bot Cache state public
  libraries/Microsoft.Bot.Builder/BotState.cs
Labels: Area: Adaptive, P0

#4606 Make cycle detection throw an exception instead of returning null.
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/Converters/DialogExpressionConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionObserver.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorerOptions.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceExplorerFixture.cs
Labels: Area: Adaptive, P0

#4669 Support null result in LG output
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/TestScriptTests/TestScriptTests_HttpRequestLuisMock.test.dialog
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/NullTolerant.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Labels: Area: LG
