Repository microsoft/botbuilder-dotnet, pull requests merged in 2020-08, with the labels that each got.

#4357 Adding xunit2017
  tests/Directory.Build.props
Labels: R10

#4368 Use Resource.Id as default Id for referenced objects
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/resources/test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/resources/test3.dialog
Labels: R10

#4376 Flush out missing doc comments in Adaptive.Testing assembly
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Actions/AssertCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/AdaptiveTestingComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestSequenceMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockHttpRequestMiddleware.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisLoader.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockedHttpClientHandler.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/MockSettingsMiddleware.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertiesMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/PropertyMocks/PropertyMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyOneOf.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/TestAction.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserConversationUpdate.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserDelay.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserSays.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserTyping.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/UserTokenMocks/UserTokenBasicMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/UserTokenMocks/UserTokenMock.cs
Labels: BF Docs, R10

#4363 Streaming: Add missing documentation
  libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj
  libraries/Microsoft.Bot.Streaming/PayloadTransport/IPayloadReceiver.cs
  libraries/Microsoft.Bot.Streaming/PayloadTransport/IPayloadSender.cs
  libraries/Microsoft.Bot.Streaming/PayloadTransport/PayloadReceiver.cs
  libraries/Microsoft.Bot.Streaming/PayloadTransport/PayloadSender.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/IAssembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/PayloadStreamAssembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/ContentStream.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/CancelDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/PayloadDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/RequestDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/ResponseDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/ResponseMessageStreamDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/StreamWrapper.cs
  libraries/Microsoft.Bot.Streaming/Payloads/HeaderSerializer.cs
  libraries/Microsoft.Bot.Streaming/Payloads/IRequestManager.cs
  libraries/Microsoft.Bot.Streaming/Payloads/IStreamManager.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Models/Header.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Models/PayloadTypes.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Models/StreamDescription.cs
  libraries/Microsoft.Bot.Streaming/Payloads/PayloadStream.cs
  libraries/Microsoft.Bot.Streaming/Payloads/RequestManager.cs
  libraries/Microsoft.Bot.Streaming/Payloads/SendOperations.cs
  libraries/Microsoft.Bot.Streaming/Payloads/StreamManager.cs
  libraries/Microsoft.Bot.Streaming/Transport/ITransport.cs
  libraries/Microsoft.Bot.Streaming/Transport/ITransportReceiver.cs
  libraries/Microsoft.Bot.Streaming/Transport/ITransportSender.cs
  libraries/Microsoft.Bot.Streaming/Transport/NamedPipe/NamedPipeClient.cs
  libraries/Microsoft.Bot.Streaming/Transport/NamedPipe/NamedPipeTransport.cs
  libraries/Microsoft.Bot.Streaming/Transport/TransportConstants.cs
  libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketTransport.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs
Labels: BF Docs, R10

#4270 Send trace for unhandled dialog events
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
Labels: no parity

#4324 Add missing documentation to all visible classes, methods, properties and parameters in LanguageGeneration
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/CustomizedMemory.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Diagnostic.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/ErrorListener.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/EvaluationOptions.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Extensions.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj
  libraries/Microsoft.Bot.Builder.LanguageGeneration/MultiLanguageLG.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Position.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Range.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/SourceRange.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Template.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateException.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateImport.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: BF Docs, R10, changes required

#4414 Added Directory.Build.props to the libraries folder and moved referen…
  Microsoft.Bot.Builder.Skills.sln
  Microsoft.Bot.Builder.sln
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj
  libraries/AdaptiveExpressions/AdaptiveExpressions.csproj
  libraries/Directory.Build.props
  libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj
  libraries/Microsoft.Bot.Builder.AI.QnA/Microsoft.Bot.Builder.AI.QnA.csproj
  libraries/Microsoft.Bot.Builder.ApplicationInsights/Microsoft.Bot.Builder.ApplicationInsights.csproj
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Microsoft.Bot.Builder.Dialogs.Adaptive.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Microsoft.Bot.Builder.Dialogs.Declarative.csproj
  libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Microsoft.Bot.Builder.LanguageGeneration.csproj
  libraries/Microsoft.Bot.Builder.TemplateManager/Microsoft.Bot.Builder.TemplateManager.csproj
  libraries/Microsoft.Bot.Builder.Testing/Microsoft.Bot.Builder.Testing.csproj
  libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
  libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
  libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
  libraries/Microsoft.Bot.Schema/Microsoft.Bot.Schema.csproj
  libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj
  libraries/integration/Directory.Build.props
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/Microsoft.Bot.Builder.Integration.AspNet.WebApi.csproj
Labels: no parity

#4394 Adding missing docs to dialog.adaptive.testing
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Actions/AssertCondition.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpRequestSequenceMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/HttpRequestMocks/HttpResponseMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/Mocks/MockLuisExtensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReply.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/AssertReplyOneOf.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/TestAction.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserActivity.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserConversationUpdate.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserDelay.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserSays.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestActions/UserTyping.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/TestScript.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/UserTokenMocks/UserTokenBasicMock.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Testing/UserTokenMocks/UserTokenMock.cs
Labels: R10

#4411 Adds new team events to Adaptive.Teams
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Schemas/TriggerConditions/Teams.OnChannelRestored.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Schemas/TriggerConditions/Teams.OnTeamArchived.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Schemas/TriggerConditions/Teams.OnTeamDeleted.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Schemas/TriggerConditions/Teams.OnTeamHardDeleted.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Schemas/TriggerConditions/Teams.OnTeamRestored.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Schemas/TriggerConditions/Teams.OnTeamUnarchived.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/TeamsComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/TriggerConditions/OnTeamsChannelRestored.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/TriggerConditions/OnTeamsTeamArchived.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/TriggerConditions/OnTeamsTeamDeleted.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/TriggerConditions/OnTeamsTeamHardDeleted.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/TriggerConditions/OnTeamsTeamRestored.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/TriggerConditions/OnTeamsTeamUnarchived.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests/ConditionalTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests/TestUtils.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.Tests/Tests/ConditionalTests/ConditionalsTests_OnTeamActivityTypes.test.dialog
  tests/tests.schema
Labels: no parity

#4335 Added Async and FxCop analyzers to Streaming project
  libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj
  libraries/Microsoft.Bot.Streaming/PayloadTransport/PayloadReceiver.cs
  libraries/Microsoft.Bot.Streaming/PayloadTransport/PayloadSender.cs
  libraries/Microsoft.Bot.Streaming/PayloadTransport/SendQueue.cs
  libraries/Microsoft.Bot.Streaming/PayloadTransport/TransportDisconnectedException.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/IAssembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/ReceiveRequestAssembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/ReceiveResponseAssembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/ContentStream.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/CancelDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/PayloadDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/RequestDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/ResponseDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Disassemblers/ResponseMessageStreamDisassembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/HeaderSerializer.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Models/Header.cs
  libraries/Microsoft.Bot.Streaming/Payloads/PayloadAssemblerManager.cs
  libraries/Microsoft.Bot.Streaming/Payloads/PayloadStream.cs
  libraries/Microsoft.Bot.Streaming/Payloads/SendOperations.cs
  libraries/Microsoft.Bot.Streaming/ReceiveRequest.cs
  libraries/Microsoft.Bot.Streaming/ReceiveRequestExtensions.cs
  libraries/Microsoft.Bot.Streaming/ReceiveResponse.cs
  libraries/Microsoft.Bot.Streaming/ReceiveResponseExtensions.cs
  libraries/Microsoft.Bot.Streaming/StreamingRequest.cs
  libraries/Microsoft.Bot.Streaming/StreamingResponse.cs
  libraries/Microsoft.Bot.Streaming/Transport/NamedPipe/NamedPipeClient.cs
  libraries/Microsoft.Bot.Streaming/Transport/NamedPipe/NamedPipeServer.cs
  libraries/Microsoft.Bot.Streaming/Transport/NamedPipe/NamedPipeTransport.cs
  libraries/Microsoft.Bot.Streaming/Transport/TransportConstants.cs
  libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketClient.cs
  libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketServer.cs
  libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketTransport.cs
  libraries/Microsoft.Bot.Streaming/Utilities/Background.cs
Labels: R10, no parity

#4390 [Declarative] Resource IDs: Update resource ID best-effort assignment to be consistent for debugging experience
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/AssemblyInfo.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Debugging/ResourceSourceContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Observers/CycleDetectionObserver.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/JsonLoadTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/resources/testWithId.dialog
Labels: P0

#4406 Fixing and suppressing build warnings
  FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/Microsoft.Bot.Builder.FunctionalTests.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/Microsoft.Bot.Builder.Adapters.Twilio.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
  libraries/Microsoft.Bot.Configuration/Microsoft.Bot.Configuration.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Startup.cs
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Microsoft.Bot.Builder.Adapters.Facebook.Tests.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.TestBot/Microsoft.Bot.Builder.Adapters.Twilio.TestBot.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.TestBot/Startup.cs
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/Microsoft.Bot.Builder.Adapters.Twilio.Tests.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft.Bot.Builder.Adapters.Webex.Tests.csproj
  tests/Directory.Build.props
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj
  tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Profiling/Microsoft.Bot.Builder.Dialogs.Adaptive.Profiling.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/ResourceTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
  tests/Microsoft.Bot.Builder.TestBot.NetCore21.Tests/Microsoft.Bot.Builder.TestBot.NetCore21.Tests.csproj
  tests/Microsoft.Bot.Builder.TestBot.Tests/Microsoft.Bot.Builder.TestBot.Tests.csproj
  tests/Microsoft.Bot.Builder.TestProtocol/Microsoft.Bot.Builder.TestProtocol.csproj
  tests/Microsoft.Bot.Builder.Testing.Tests/Microsoft.Bot.Builder.Testing.Tests.csproj
  tests/Microsoft.Bot.Builder.Tests/Skills/SkillHandlerTests.cs
  tests/Microsoft.Bot.Connector.Tests/Microsoft.Bot.Connector.Tests.csproj
  tests/Microsoft.Bot.Streaming.Tests/Microsoft.Bot.Streaming.Tests.csproj
  tests/Microsoft.Bot.Streaming.Tests/NamedPipeTests.cs
  tests/Skills/Bot3/Bot3.csproj
  tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests.csproj
Labels: R10

#4432 Fix schema bugs in Microsoft.Ask.
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.Ask.schema
  tests/tests.schema
Labels: R10

#4439 Cherry pick for #4436
  Microsoft.Bot.Builder.sln
  libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj
  tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests.csproj
  tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/MockResolver.cs
  tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorTests.cs
Labels: no parity

#4457 Updated issue templates to apply default labels
  .github/ISSUE_TEMPLATE/-net-sdk-bug.md
  .github/ISSUE_TEMPLATE/-net-sdk-feature-request.md
Labels: no parity

#4480 Set WaterfallStepContext.Parent correctly
  libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Labels: no parity

#4486 4.10 cherry-pick of Set WaterfallStepContext.Parent correctly (#4480) also including 'Enable schema tests' cherry pick
  libraries/Microsoft.Bot.Builder.Dialogs/WaterfallStepContext.cs
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Labels: no parity

#4516 fix the issue while multiline content starts with "#"
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileLexer.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGFileParser.g4
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/Multiline.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Labels: Area: LG

#4529 Make "merge" support any kind of object type
  libraries/AdaptiveExpressions/BuiltinFunctions/Merge.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: Area: Adaptive expression
