Repository microsoft/botbuilder-dotnet, pull requests merged in 2020-06, with the labels that each got.

#3898 [LG] Move "EXPRESSION" in LG from lexer to parser
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Evaluator.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Extensions.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplateLexer.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/LGTemplateParser.g4
  libraries/Microsoft.Bot.Builder.LanguageGeneration/StaticChecker.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/ParseTreeTest.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesParseTreeTest.cs
Labels: R10

#4031 Update doc XML
  libraries/Microsoft.Bot.Builder/AdapterExtensions.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
Labels: docs

#3899 [Expression] Support lambda style expression
  libraries/AdaptiveExpressions/parser/ExpressionAntlrLexer.g4
  libraries/AdaptiveExpressions/parser/ExpressionAntlrParser.g4
  libraries/AdaptiveExpressions/parser/ExpressionParser.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: R10, expression

#4078 Add aadGroupId to TeamInfo
  libraries/Microsoft.Bot.Schema/Teams/Generated/TeamInfo.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs
Labels: no parity

#4110 Enables FxCop Analyzer for the Connector library
  libraries/Microsoft.Bot.Connector/AttachmentsEx.cs
  libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs
  libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs
  libraries/Microsoft.Bot.Connector/Authentication/ChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/EndorsementsRetriever.cs
  libraries/Microsoft.Bot.Connector/Authentication/EnterpriseChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/GovernmentChannelValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/Retry.cs
  libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/ThrottleException.cs
  libraries/Microsoft.Bot.Connector/Authentication/TimeSpanExtensions.cs
  libraries/Microsoft.Bot.Connector/Channels.cs
  libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
  libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
  libraries/Microsoft.Bot.Connector/OAuthClientConfig.cs
  libraries/Microsoft.Bot.Connector/OAuthClientOld.cs
Labels: no parity

#4082 Migrates Tests tests to Xunit
  tests/Microsoft.Bot.Builder.Tests/Microsoft.Bot.Builder.Tests.csproj
  tests/Microsoft.Bot.Builder.Tests/Skills/SkillHandlerTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityExtensionsTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerBadRequestTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerHidingTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerNotImplementedTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
Labels: R10

#3935 Fixes issue #3960 [QnAMaker] [DotNet] Implementing QnAMaker's precise answering capability as an additional feature for BotFramework users
  libraries/Microsoft.Bot.Builder.AI.QnA/AnswerSpanRequest.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/AnswerSpanResponse.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/QnAMakerTraceInfo.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/QueryResult.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnADialogResponseOptions.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Schemas/Microsoft.QnAMakerDialog.schema
  libraries/Microsoft.Bot.Builder.AI.QnA/Schemas/Microsoft.QnAMakerRecognizer.schema
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnACardBuilder.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerCardEqualityComparer.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerRecognizerTests.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/TestData/QnaMaker_ReturnAnswersWithPreciseAnswer.json
Labels: changes required

#4130 Migrating Schema to Xunit
  tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs
  tests/Microsoft.Bot.Schema.Tests/CardActionTest.cs
  tests/Microsoft.Bot.Schema.Tests/EntitySchemaValidationTest.cs
  tests/Microsoft.Bot.Schema.Tests/Microsoft.Bot.Schema.Tests.csproj
  tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs
Labels: R10, no parity

#4123 Updates to Facebook Adapter
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapterOptions.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/AttachmentPayload.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookAttachment.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookBotUser.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookEntry.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookPostback.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookQuickReply.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookRecipient.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookResponseEvent.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookResponseOk.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookPassThreadControl.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookTakeThreadControl.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookThreadControl.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/HandoverConstants.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Templates/Button.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Templates/DefaultAction.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Message.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Microsoft.Bot.Builder.Adapters.Facebook.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookAdapterTests.cs
Labels: changes required, no parity

#4063 Add OnContinueConversation trigger and ContinueConversationLater action
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  libraries/Microsoft.Bot.Builder.Azure/Queues/ContinueConversationLater.cs
  libraries/Microsoft.Bot.Builder.Azure/Schemas/AzureQueues.ContinueConversationLater.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnContinueConversation.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnContinueConversation.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/AzureQueueTests.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/Microsoft.Bot.Builder.Azure.Tests.csproj
  tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs
  tests/tests.schema
Labels: changes required

#4126 Add ToAttachment method for OAuthCard
  libraries/Microsoft.Bot.Schema/CardEx.cs
  tests/Microsoft.Bot.Schema.Tests/CardExTest.cs
Labels: no parity

#4181 Port LanguageGeneration to Xunit
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/MultilanguageLGTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesParseTreeTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Labels: BF Code Quality, R10, no parity

#4083 Further improve LG's performance
  libraries/Microsoft.Bot.Builder.LanguageGeneration/SourceRange.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/Templates.cs
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplatesParser.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/CrudInit.lg
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Microsoft.Bot.Builder.LanguageGeneration.Tests.csproj
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Labels: LG, enhancement

#4150 Add LinkToMessage in MessageActionsPayload class
  libraries/Microsoft.Bot.Schema/Teams/Generated/MessageActionsPayload.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/MessageActionsPayloadTests.cs
Labels: changes required, no parity

#4127 Add missing code docs for the webex adapter
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/AttachmentActionData.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexMessageRequest.cs
Labels: no parity

#4135 Porting Transcript tests to Xunit
  tests/Microsoft.Bot.Builder.Tests/TranscriptUtilities.cs
  tests/Microsoft.Bot.Builder.Transcripts.Tests/CoreExtensionsTests.cs
  tests/Microsoft.Bot.Builder.Transcripts.Tests/CoreTests.cs
  tests/Microsoft.Bot.Builder.Transcripts.Tests/DialogsTests.cs
  tests/Microsoft.Bot.Builder.Transcripts.Tests/Microsoft.Bot.Builder.Transcripts.Tests.csproj
Labels: BF Code Quality, R10, no parity

#4151 Refactoring AI Luis V3 to Xunit
  tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisApplicationTests.cs
  tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisV3OracleTests.cs
  tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Microsoft.Bot.Builder.AI.LuisV3.Tests.csproj
Labels: BF Code Quality, R10, no parity

#4189 Update missing code docs for the Azure library
  libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  libraries/Microsoft.Bot.Builder.Azure/Queues/ContinueConversationLater.cs
Labels: no parity

#3813 [Adaptive] Add Binary Data Parsing For Http Request
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.HttpRequest.schema
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
Labels: Adaptive, R10
