Repository microsoft/botbuilder-dotnet, pull requests merged in 2021-03, with the labels that each got.

#5287 Log missing update activity and fix infinite loop
  libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
  libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/TranscriptStoreBaseTests.cs
Labels: no parity

#4880 Add support of Expressions in BeginDialog Actions
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveComponentRegistration.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Converters/DialogSetConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/Expressions/Converters/DialogExpressionConverter.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.BeginDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Microsoft.AdaptiveDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Schemas/Microsoft.IDialog.schema
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_BeginDialogWithExpr.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_BeginDialogWithExpr2.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_BeginDialogWithExpr3.test.dialog
  tests/tests.schema
Labels: Area: Adaptive

#5368 Hand-off: add converters to support hand off action
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveBotComponent.cs
Labels: Automation: No parity

#5369 Orchestrator: make a component by adding bf-component tag
  libraries/Microsoft.Bot.Builder.AI.Orchestrator/Microsoft.Bot.Builder.AI.Orchestrator.csproj
Labels: Automation: No parity

#5374 Adds skill processing for commands
  libraries/Microsoft.Bot.Builder/Skills/SkillHandlerImpl.cs
  tests/Microsoft.Bot.Builder.Tests/Skills/CloudSkillHandlerTests.cs
Labels: Automation: No parity, no parity
