Repository microsoft/botbuilder-dotnet, pull requests merged in 2021-02, with the labels that each got.

#5157 remove references to TrustServiceUrl
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenValidation.cs
  libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs
  libraries/Microsoft.Bot.Connector/ConversationsEx.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotFrameworkHttpAdapter.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenValidationTests.cs
Labels: Automation: Parity with js

#5142 Fix deliveryMode.ExpectReplies for skills.
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/BotFrameworkHttpClientTests.cs
Labels: Area: Skills, P0

#5154 Use double.Epsilon for equal check in expression
  libraries/AdaptiveExpressions/BuiltinFunctions/Equal.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/Sqrt.cs
Labels: Area: Adaptive expression

#5170 fix: null audiences/OAuthScopes shouldn't break streaming
  libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs
  tests/Microsoft.Bot.Builder.Tests/BotFrameworkHttpAdapterBaseTests.cs
Labels: Automation: No parity

#5155 Add 'any' and 'all' prebuilt function
  libraries/AdaptiveExpressions/BuiltinFunctions/All.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/Any.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/Foreach.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/NotEqual.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/Select.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/Where.cs
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/ExpressionType.cs
  libraries/AdaptiveExpressions/FunctionUtils.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: Area: Adaptive expression
