Repository microsoft/botbuilder-dotnet, pull requests merged in 2021-01, with the labels that each got.

#5061 Remove comment only ProductInfoHeaderValue
  libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs
  tests/Microsoft.Bot.Connector.Tests/ConnectorClientTest.cs
Labels: no parity

#5079 Add add-upgrade and remove-upgrade for InstallationUpdate
  libraries/Microsoft.Bot.Builder/ActivityHandler.cs
  tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
Labels: Automation: No parity

#5080 Add verbosity for diagnosis of Webex Functional tests failures
  build/yaml/botbuilder-dotnet-ci-webex-test.yml
Labels: Automation: No parity

#5122 Merge Partial Classes into Single File
  libraries/Microsoft.Bot.Schema/ActivityTypes.cs
  libraries/Microsoft.Bot.Schema/Attachment.cs
  libraries/Microsoft.Bot.Schema/AttachmentEx.cs
  libraries/Microsoft.Bot.Schema/CardAction.cs
  libraries/Microsoft.Bot.Schema/CardActionEx.cs
  libraries/Microsoft.Bot.Schema/ChannelAccount.cs
  libraries/Microsoft.Bot.Schema/ChannelAccountEx.cs
  libraries/Microsoft.Bot.Schema/ConversationAccount.cs
  libraries/Microsoft.Bot.Schema/ConversationAccountEx.cs
  libraries/Microsoft.Bot.Schema/ConversationReference.cs
  libraries/Microsoft.Bot.Schema/ConversationReferenceEx.cs
  libraries/Microsoft.Bot.Schema/Entity.cs
  libraries/Microsoft.Bot.Schema/EntityEx.cs
  libraries/Microsoft.Bot.Schema/GeoCoordinates.cs
  libraries/Microsoft.Bot.Schema/GeoCoordinatesEx.cs
  libraries/Microsoft.Bot.Schema/Mention.cs
  libraries/Microsoft.Bot.Schema/MentionEx.cs
  libraries/Microsoft.Bot.Schema/MicrosoftPayMethodData.cs
  libraries/Microsoft.Bot.Schema/MicrosoftPayMethodDataEx.cs
  libraries/Microsoft.Bot.Schema/PaymentRequest.cs
  libraries/Microsoft.Bot.Schema/PaymentRequestEx.cs
  libraries/Microsoft.Bot.Schema/Place.cs
  libraries/Microsoft.Bot.Schema/PlaceEx.cs
  libraries/Microsoft.Bot.Schema/SigninCard.cs
  libraries/Microsoft.Bot.Schema/SigninCardEx.cs
  libraries/Microsoft.Bot.Schema/SuggestedActions.cs
  libraries/Microsoft.Bot.Schema/SuggestedActionsEx.cs
Labels: Automation: No parity

#5096 added disposed
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Builder/TokenResolver.cs
  libraries/Microsoft.Bot.Builder/TurnContext.cs
  libraries/Microsoft.Bot.Builder/TurnContextStateCollection.cs
Labels: Automation: No parity

#5119 [Expression]Add abs and sqrt built- in function
  libraries/AdaptiveExpressions/BuiltinFunctions/Abs.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/Sqrt.cs
  libraries/AdaptiveExpressions/ExpressionFunctions.cs
  libraries/AdaptiveExpressions/ExpressionType.cs
  tests/AdaptiveExpressions.Tests/BadExpressionTests.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: Area: Adaptive expression
