Repository microsoft/botbuilder-dotnet, pull requests merged in 2022-05, with the labels that each got.

#6310 Update pipeline to coveralls.net v 3.0.0
  build/PublishToCoveralls.ps1
  build/yaml/ci-test-steps.yml
Labels: Area: Engineering, Automation: No parity

#6298 Add oAuthEndpoint to _oAuthClients cache key
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterOAuthTests.cs
  tests/Microsoft.Bot.Builder.Tests/MockAppCredentials.cs
Labels: Automation: No parity

#6316 [#6229] Add descriptions to ARM template parameters files
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/README.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/README.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/DeploymentTemplates/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/DeploymentTemplates/README.md
Labels: Automation: No parity

#6321 Add ApplicationName to CosmosDb client options for UserAgent
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
Labels: Automation: Parity all

#6322 Fix create-botbuilder-parity-issues.yml workflow
  .github/workflows/create-botbuilder-parity-issues.yml
Labels: Area: Engineering, ExemptFromDailyDRIReport, Automation: No parity

#6325 Handle DialogEvents.RepromptDialog in ForEachElement
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
Labels: Automation: No parity

#6327 Cherry-Pick to 4.16: Handle DialogEvents.RepromptDialog in ForEachElement (#6325)
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
Labels: Automation: No parity

#6326 BotBuilder-DotNet-Webex-Functional-Test-yaml intermittently fails
  build/yaml/botbuilder-dotnet-ci-webex-test.yml
Labels: bug, Area: Engineering, Automation: No parity

#6329 Fix task 'Verify publish compat results success'
  build/yaml/botbuilder-dotnet-ci.yml
  build/yaml/ci-post-to-github-steps.yml
Labels: bug, Area: Engineering, Automation: No parity

#6335 fix: Add oAuthEndpoint to _oAuthClients cache key (#6298)
  libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs
  tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterOAuthTests.cs
  tests/Microsoft.Bot.Builder.Tests/MockAppCredentials.cs
Labels: Automation: No parity

#6301 [#6292] Add unit tests for AzureBlobStorage
  libraries/Microsoft.Bot.Builder.Azure/AssemblyInfo.cs
  libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobStorageTests.cs
Labels: Automation: No parity

#6314 [#5678] Channels "enumeration" is out of date
  libraries/Microsoft.Bot.Connector/Channels.cs
Labels: Automation: No parity

#6341 Changed min requirements for some libraries in the netstandard targetets
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj
  libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
  libraries/Microsoft.Bot.Connector.Streaming/Microsoft.Bot.Connector.Streaming.csproj
  libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
  libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
Labels: Automation: No parity

#6342 Changed min requirements for some libraries in the netstandard target back to 2.1 versions (#6341)
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj
  libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Microsoft.Bot.Builder.Dialogs.Debugging.csproj
  libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
  libraries/Microsoft.Bot.Connector.Streaming/Microsoft.Bot.Connector.Streaming.csproj
  libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
  libraries/Microsoft.Bot.Streaming/Microsoft.Bot.Streaming.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Microsoft.Bot.Builder.Integration.AspNet.Core.csproj
Labels: Automation: No parity

#6343 [#6339] Mark deprecated channels as obsolete in Channels enum
  libraries/Microsoft.Bot.Connector/Channels.cs
Labels: Automation: No parity
