Repository microsoft/botbuilder-dotnet, pull requests merged in 2022-07, with the labels that each got.

#6370 [#6368] SDK uses deprecated Microsoft.Azure.DocumentDB.Core library
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbCustomClientOptions.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs
  libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorageOptions.cs
  libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
  tests/Microsoft.Bot.Builder.Azure.Tests/CosmosDbStorageTests.cs
Labels: Automation: Parity with js

#6397 [#6392] Bump Newtonsoft.Json from 12.0.3 to 13.0.1 - Set MaxDepth property (1/4)
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/Json.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/JsonStringify.cs
  libraries/AdaptiveExpressions/BuiltinFunctions/String.cs
  libraries/AdaptiveExpressions/Expression.cs
  libraries/AdaptiveExpressions/ExpressionProperties/ExpressionProperty.cs
  libraries/AdaptiveExpressions/Memory/SimpleObjectMemory.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/CustomQuestionAnswering.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/GenerateAnswerUtils.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/LanguageServiceUtils.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/TrainUtils.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotMessageHandler.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs
Labels: Automation: No parity

#6399 [#6392] Bump Newtonsoft.Json from 12.0.3 to 13.0.1 - Set MaxDepth property (3/4)
  libraries/Microsoft.Bot.Configuration/BotConfiguration.cs
  libraries/Microsoft.Bot.Connector.Streaming/Transport/TransportHandler.cs
  libraries/Microsoft.Bot.Connector/Authentication/BotFrameworkClientImpl.cs
  libraries/Microsoft.Bot.Connector/Authentication/UserTokenClient.cs
  libraries/Microsoft.Bot.Connector/ConnectorClient.cs
  libraries/Microsoft.Bot.Connector/OAuthClientOld.cs
  libraries/Microsoft.Bot.Connector/Teams/TeamsConnectorClient.cs
  libraries/Microsoft.Bot.Schema/Entity.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/ReceiveRequestAssembler.cs
  libraries/Microsoft.Bot.Streaming/Payloads/Assemblers/ReceiveResponseAssembler.cs
  libraries/Microsoft.Bot.Streaming/ReceiveResponseExtensions.cs
  libraries/Microsoft.Bot.Streaming/SerializationSettings.cs
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/Bots/PrimaryBot.cs
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Bots/EchoBot.cs
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Bots/EchoBot.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Contoso_App.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Contoso_App_V3.cs
  tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Contoso_App.cs
  tests/Microsoft.Bot.Builder.TestBot.Shared/Bots/DialogAndWelcomeBot.cs
  tests/Microsoft.Bot.Builder.TestBot.Shared/CognitiveModels/FlightBooking.cs
  tests/Microsoft.Bot.Builder.TestBot.Shared/HttpHelper.cs
  tests/Microsoft.Bot.Builder.TestBot.WebApi/Bots/DialogAndWelcomeBot.cs
  tests/Microsoft.Bot.Connector.Streaming.Tests.Client/Program.cs
  tests/Microsoft.Bot.Streaming.Tests/Utilities/MockBot.cs
  tests/Skills/Bot1/Bot1.cs
  tests/Skills/Bot2/Bot2.cs
Labels: Automation: No parity

#6400 [#6392] Bump Newtonsoft.Json from 12.0.3 to 13.0.1 - Set MaxDepth property (4/4)
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Bots/DialogAndWelcomeBot.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CognitiveModels/FlightBooking.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Bots/DialogAndWelcomeBot.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CognitiveModels/FlightBooking.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Bots/DialogAndWelcomeBot.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CognitiveModels/FlightBooking.cs
Labels: Automation: No parity

#6337 fix: MeetingDetails dates are nullable
  libraries/Microsoft.Bot.Schema/Teams/MeetingDetails.cs
Labels: Automation: Parity all, BREAKING

#6369 Fix PublishToCoveralls.ps1 for Windows 2022
  build/PublishToCoveralls.ps1
Labels: Automation: No parity

#6360 Add settings.selectedChannel to TeamsChannelData and Type to ChannelInfo and TeamDetails
  libraries/Microsoft.Bot.Builder/Teams/TeamsActivityExtensions.cs
  libraries/Microsoft.Bot.Schema/Teams/ChannelInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamDetails.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsChannelData.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsChannelDataSettings.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityExtensionsTests.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/ChannelInfoTests.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/TeamDetailsTests.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs
Labels: Automation: Parity with js

#6401 minor: ConversationAccount/IsGroup: Correct typo in docs.
  libraries/Microsoft.Bot.Schema/ConversationAccount.cs
Labels: Automation: No parity

#6356 Add Teams read receipt event
  libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
  libraries/Microsoft.Bot.Schema/Teams/ReadReceiptInfo.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/ReadReceiptInfoTests.cs
Labels: Automation: Parity with js

#6394 Use ActionScope.Actions in ForEachElement
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
Labels: Automation: No parity

#6410 Testing narrow appinsights update
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj
Labels: Automation: No parity

#6404 Catch HttpRequestException in HttpRequest
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
Labels: Automation: Parity all

#6412 Lowered AppInsights requirements
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj
Labels: Automation: No parity

#6365 [#6355] ContinueDialog fails to find dynamically loaded dialog after bot restart
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
Labels: Automation: No parity

#6402 Revert "Multiple voice tags can now be added in speak field (#6315)"
  libraries/Microsoft.Bot.Builder/SetSpeakMiddleware.cs
  tests/Microsoft.Bot.Builder.Tests/SetSpeakMiddlewareTests.cs
Labels: Automation: No parity

#6418 Corrected VSIX ARM template readmes and project templates to include …
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/DeploymentTemplates/DeployUseExistResourceGroup/readme.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/DeploymentTemplates/DeployWithNewResourceGroup/readme.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates/DeployUseExistResourceGroup/readme.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates/DeployWithNewResourceGroup/readme.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/DeploymentTemplates/DeployUseExistResourceGroup/readme.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/DeploymentTemplates/DeployWithNewResourceGroup/readme.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate
Labels: Automation: No parity

#6416 [#6306] NamedPipe could not reconnect correctly when disconnected unexpectedly
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs
Labels: Automation: No parity

#6420 Reasonable ARM Template readme formatting
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/DeployUseExistResourceGroup/readme.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/DeployWithNewResourceGroup/readme.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/DeployUseExistResourceGroup/readme.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/DeployWithNewResourceGroup/readme.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/DeployUseExistResourceGroup/readme.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/DeployWithNewResourceGroup/readme.md
Labels: Automation: No parity

#6425 README version to 4.18
  README.md
Labels: Automation: No parity
