Repository microsoft/botbuilder-dotnet, pull requests merged in 2022-08, with the labels that each got.

#6429 4.17.1 bump for generators
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj
Labels: Automation: No parity

#6435 [#6434] Priority broken for RegexRecognizer
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/RegexRecognizer.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/RegexRecognizerTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/RegexRecognizerTests/RegexRecognizerTests_Priority.test.dialog
Labels: Automation: Parity with js

#6431 [#5800] AdaptiveExpression Bool function is not very useful because it doesn't convert anything but ints
  libraries/AdaptiveExpressions/BuiltinFunctions/Bool.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: Automation: Parity with js

#6426 [#6354] isMatch adaptive expression returns error when value is null or empty string
  libraries/AdaptiveExpressions/BuiltinFunctions/IsMatch.cs
  tests/AdaptiveExpressions.Tests/ExpressionParserTests.cs
Labels: Automation: Parity with js

#6448 [#6428] Adaptive ForEachElement loop's incorrectly when changes cause ContinueDialogAsync to be recalled
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
Labels: Automation: No parity

#6449 Support passing sas token url's for token service
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Schema/OAuthCard.cs
  libraries/Microsoft.Bot.Schema/SignInResource.cs
  libraries/Microsoft.Bot.Schema/TokenPostResource.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
Labels: Automation: Parity with js

#6452 [#6430] Adaptive ForEachElement does not exit when child action CancelAllDialogs is called
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Foreach_Nested_WithCancel.test.dialog
Labels: Automation: No parity

#6455 Removed Owin reference
  tests/integration/Microsoft.Bot.ApplicationInsights.WebApi.Tests/Microsoft.Bot.ApplicationInsights.WebApi.Tests.csproj
Labels: Automation: No parity

#6456 Clean up ExtractCompressNuGet.ps1 in dotnet
  build/ExtractCompressNuGet.ps1
Labels: Area: Engineering, Automation: No parity

#6443 [#6432] TeamsInfo.GetMemberAsync(...) doesn't work properly in Skill Bot scenario, it returns http 405 error
  libraries/Microsoft.Bot.Builder/ChannelServiceHandlerBase.cs
  libraries/Microsoft.Bot.Builder/Skills/CloudSkillHandler.cs
  libraries/Microsoft.Bot.Builder/Skills/SkillHandlerImpl.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ChannelServiceController.cs
  tests/Microsoft.Bot.Builder.Tests/Skills/CloudSkillHandlerTests.cs
Labels: Automation: Parity with js

#6444 [#6433] Error in AdaptiveDialog.ContinueActionAsync with native dialog SDK
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/BaseInvokeDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_LoadDialogFromProperty.test.dialog
Labels: Automation: No parity
