Repository microsoft/botbuilder-dotnet, pull requests merged in 2022-02, with the labels that each got.

#6151 Cherry-pick to 4.15: Fix for when Actions are updated in ForEachElement (#6143)
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.Foreach.schema
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/ActionTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_Foreach_WithEvent.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestNestedForeachWithPromptCachedItems.test.dialog
  tests/tests.schema
Labels: no parity

#6146 Add verify-pr-labels GitHub workflow
  .github/workflows/verify-pr-labels.yml
  actions/README.md
  actions/verify-pr-labels/action.yml
  actions/verify-pr-labels/index.js
  actions/verify-pr-labels/package.json
  actions/verify-pr-labels/yarn.lock
Labels: Automation: No parity

#6158 Fix labels casing in parity check action
  actions/verify-pr-labels/index.js
Labels: Automation: No parity

#6159 Move TestAdapter and TestFlow to Microsoft.Bot.Builder.Testing package.
  libraries/Microsoft.Bot.Builder.Testing/Adapters/TestAdapter.cs
  libraries/Microsoft.Bot.Builder.Testing/Adapters/TestFlow.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/Microsoft.Bot.Builder.AI.Luis.Tests.csproj
  tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests.csproj
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/Microsoft.Bot.Builder.AI.QnA.Tests.csproj
  tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/Microsoft.Bot.Builder.AI.LuisV3.Tests.csproj
  tests/Microsoft.Bot.Builder.ApplicationInsights.Tests/Microsoft.Bot.Builder.ApplicationInsights.Tests.csproj
  tests/Microsoft.Bot.Builder.Dialogs.Tests/Microsoft.Bot.Builder.Dialogs.Tests.csproj
  tests/Microsoft.Bot.Builder.Tests.Common/Microsoft.Bot.Builder.Tests.Common.csproj
  tests/integration/Microsoft.Bot.ApplicationInsights.Core.Tests/Microsoft.Bot.ApplicationInsights.Core.Tests.csproj
Labels: Automation: Parity with js

#6160 Ensure EndDialog action within a ForEachElement will end the dialog
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/TestForeachWithEndDialog.test.dialog
Labels: Automation: Parity with js

#6166 DotNet pipeline tweaks
  build/yaml/ci-test-steps.yml
Labels: Automation: No parity

#6162 [#6099] Remove low impact FxCop exclusions - Sample cases (1/2)
  libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/FeedbackRecords.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/TrainUtils.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Recognizer.cs
  libraries/Microsoft.Bot.Builder/ActivityHandler.cs
  libraries/Microsoft.Bot.Builder/BotAssert.cs
  libraries/Microsoft.Bot.Builder/BotState.cs
  libraries/Microsoft.Bot.Builder/CachedBotState.cs
  libraries/Microsoft.Bot.Builder/IMiddleware.cs
  libraries/Microsoft.Bot.Builder/InvokeResponseException.cs
  libraries/Microsoft.Bot.Builder/TelemetryLoggerMiddleware.cs
  libraries/Microsoft.Bot.Connector/AttachmentsEx.cs
  libraries/Microsoft.Bot.Schema/ActivityEx.cs
  libraries/Microsoft.Bot.Streaming/Payloads/RequestManager.cs
  libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Labels: Automation: No parity

#6169 V5 general cleanup of deprecated and duplicate classes
  CodeCoverage.runsettings
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs
  libraries/Microsoft.Bot.Builder/Integration/BotFrameworkPaths.cs
  libraries/Microsoft.Bot.Builder/Integration/MessageSerializerSettings.cs
  libraries/Microsoft.Bot.Builder/InvokeResponse.cs
  libraries/Microsoft.Bot.Builder/InvokeResponse{T}.cs
  libraries/Microsoft.Bot.Builder/QueueStorage.cs
  libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
  libraries/Storage/Microsoft.Bot.Builder.Azure.Blobs/Microsoft.Bot.Builder.Azure.Blobs.csproj
  libraries/Storage/Microsoft.Bot.Builder.Azure.Cosmos/Microsoft.Bot.Builder.Azure.Cosmos.csproj
  tests/Microsoft.Bot.Builder.Tests/Integration.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs
Labels: Automation: Parity with js

#6155 Add continueOnError: true for publish
  build/yaml/ci-test-steps.yml
Labels: Automation: No parity

#6178 Update generators to 4.15.2
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj
  generators/dotnet-templates/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/HOW_TO_VERSION.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/source.extension.vsixmanifest
Labels: Automation: No parity

#6177 Add Obsolete attribute to DialogManager
  libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
Labels: Automation: Parity with js

#6185 [#6099] Remove low impact FxCop exclusions - Rule CA1052
  libraries/Microsoft.Bot.Builder.AI.QnA/Models/RankerTypes.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceRecognizers.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/Tokenizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogEvents.cs
  libraries/Microsoft.Bot.Builder/ActivityFactory.cs
  libraries/Microsoft.Bot.Connector/Channels.cs
  libraries/Microsoft.Bot.Schema/ErrorCodes.cs
Labels: Automation: No parity

#6192 [Cherry-pick to 4.15] [#6018] Move Dotnet generators from Samples to "generators" - dotnet-templates - Echo Bot (#6049)
  generators/dotnet-templates/HOW_TO_VERSION.md
  generators/dotnet-templates/LICENSE
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/LICENSE.txt
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/dotnetcli.host.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/AdapterWithErrorHandler.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Bots/EchoBot.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Controllers/BotController.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/new-rg-parameters.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/preexisting-rg-parameters.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/template-with-new-rg.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/template-with-preexisting-rg.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Program.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Properties/launchSettings.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/README.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Startup.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/appsettings.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/wwwroot/default.html
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/nuget_icon.png
  generators/dotnet-templates/README.md
Labels: Automation: No parity

#6193 [Cherry-pick to 4.15] Move Dotnet generators from Samples to "generators" - dotnet-templates - Empty Bot (#6050)
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/LICENSE.txt
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/dotnetcli.host.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.vscode/launch.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.vscode/tasks.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/AdapterWithErrorHandler.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Controllers/BotController.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/new-rg-parameters.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/preexisting-rg-parameters.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/template-with-new-rg.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/DeploymentTemplates/template-with-preexisting-rg.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/EmptyBot.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Program.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Properties/launchSettings.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/README.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Startup.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/appsettings.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/wwwroot/default.htm
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/nuget_icon.png
Labels: Automation: No parity

#6194 [Cherry-pick to 4.15] Move Dotnet generators from Samples to "generators" - dotnet-templates - Core Bot (#6051)
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/LICENSE.txt
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/dotnetcli.host.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Bots/DialogAndWelcomeBotTests.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Bots/DialogBotTests.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Common/BotTestBase.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Common/README.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Common/SimpleMockFactory.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Controllers/BotControllerTests.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/BookingDialogTests.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/CancelAndHelpDialogTests.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/DateResolverDialogTests.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/MainDialogTests.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/BookingDialogTestCase.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/BookingDialogTestsDataGenerator.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/DateResolverDialogTestCase.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/DateResolverDialogTestsDataGenerator.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/FlightFromCdgToJfk.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/FlightFromMadridToChicago.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/FlightFromParisToNewYork.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/FlightToMadrid.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Dialogs/TestData/README.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/Properties/launchSettings.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/README.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/AdapterWithErrorHandler.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/BookingDetails.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Bots/DialogAndWelcomeBot.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Bots/DialogBot.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Cards/welcomeCard.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CognitiveModels/FlightBooking.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CognitiveModels/FlightBooking.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CognitiveModels/FlightBookingEx.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Controllers/BotController.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/new-rg-parameters.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/preexisting-rg-parameters.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/template-with-new-rg.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/DeploymentTemplates/template-with-preexisting-rg.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Dialogs/BookingDialog.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Dialogs/CancelAndHelpDialog.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Dialogs/DateResolverDialog.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Dialogs/MainDialog.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/FlightBookingRecognizer.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Program.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Properties/launchSettings.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/README.md
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/Startup.cs
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/appsettings.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/wwwroot/default.htm
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/nuget_icon.png
Labels: Automation: No parity

#6195 [Cherry-pick to 4.15] Move Dotnet generators from Samples to "generators" - VSIX - Echo Bot (#6052)
  generators/vsix-vs-win/BotBuilderVSIX-V4/BotBuilderTemplatesVSIX.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/BotBuilderTemplatesVSIX.sln
  generators/vsix-vs-win/BotBuilderVSIX-V4/HOW_TO_VERSION.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/LICENSE.txt
  generators/vsix-vs-win/BotBuilderVSIX-V4/Package.ico
  generators/vsix-vs-win/BotBuilderVSIX-V4/Properties/AssemblyInfo.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/Properties/Resources.Designer.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/Properties/Resources.resx
  generators/vsix-vs-win/BotBuilderVSIX-V4/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/Template.ico
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/AdapterWithErrorHandler.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/Bots/EchoBot.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/Controllers/BotController.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates/new-rg-parameters.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates/preexisting-rg-parameters.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates/template-with-new-rg.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/DeploymentTemplates/template-with-preexisting-rg.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot-4-3.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/Program.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/Properties/launchSettings.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/Startup.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/appsettings.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/wwwroot/default.htm
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/MyTemplate.__vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/__TemplateIcon.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/vstg0001.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/__PreviewImage.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/__TemplateIcon.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/app.config
  generators/vsix-vs-win/BotBuilderVSIX-V4/packages.config
  generators/vsix-vs-win/BotBuilderVSIX-V4/source.extension.vsixmanifest
Labels: Automation: No parity

#6196 [Cherry-pick to 4.15] Move Dotnet generators from Samples to "generators" - VSIX - Empty Bot (#6053)
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/AdapterWithErrorHandler.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/Controllers/BotController.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/DeploymentTemplates/new-rg-parameters.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/DeploymentTemplates/preexisting-rg-parameters.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/DeploymentTemplates/template-with-new-rg.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/DeploymentTemplates/template-with-preexisting-rg.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot-4-3.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/Program.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/Properties/launchSettings.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/Startup.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/appsettings.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/wwwroot/default.htm
Labels: Automation: No parity

#6197 [Cherry-pick to 4.15] Move Dotnet generators from Samples to "generators" - VSIX - Core Bot (#6054)
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/AdapterWithErrorHandler.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/BookingDetails.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Bots/DialogAndWelcomeBot.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Bots/DialogBot.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Cards/welcomeCard.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CognitiveModels/FlightBooking.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CognitiveModels/FlightBooking.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CognitiveModels/FlightBookingEx.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Controllers/BotController.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot-4-3.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/DeploymentTemplates/new-rg-parameters.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/DeploymentTemplates/preexisting-rg-parameters.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/DeploymentTemplates/template-with-new-rg.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/DeploymentTemplates/template-with-preexisting-rg.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Dialogs/BookingDialog.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Dialogs/CancelAndHelpDialog.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Dialogs/DateResolverDialog.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Dialogs/MainDialog.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/FlightBookingRecognizer.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Program.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Properties/launchSettings.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/Startup.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/appsettings.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/wwwroot/default.htm
Labels: Automation: No parity

#6198 [Cherry-pick to 4.15] Move Dotnet generators from Samples to "generators" - VSIX - Core Bot with Tests (#6055)
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Bots/DialogAndWelcomeBotTests.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Bots/DialogBotTests.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Common/BotTestBase.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Common/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Common/SimpleMockFactory.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Controllers/BotControllerTests.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/BookingDialogTests.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/CancelAndHelpDialogTests.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/DateResolverDialogTests.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/MainDialogTests.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/BookingDialogTestCase.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/BookingDialogTestsDataGenerator.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/DateResolverDialogTestCase.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/DateResolverDialogTestsDataGenerator.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/FlightFromCdgToJfk.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/FlightFromMadridToChicago.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/FlightFromParisToNewYork.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/FlightToMadrid.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/AdapterWithErrorHandler.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/BookingDetails.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Bots/DialogAndWelcomeBot.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Bots/DialogBot.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Cards/welcomeCard.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CognitiveModels/FlightBooking.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CognitiveModels/FlightBooking.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CognitiveModels/FlightBookingEx.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Controllers/BotController.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.png
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/DeploymentTemplates/new-rg-parameters.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/DeploymentTemplates/preexisting-rg-parameters.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/DeploymentTemplates/template-with-new-rg.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/DeploymentTemplates/template-with-preexisting-rg.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Dialogs/BookingDialog.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Dialogs/CancelAndHelpDialog.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Dialogs/DateResolverDialog.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Dialogs/MainDialog.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/FlightBookingRecognizer.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Program.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Properties/launchSettings.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/Startup.cs
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/appsettings.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/wwwroot/default.htm
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate
Labels: Automation: No parity

#6203 [Cherry-pick to 4.15] Update generators to 4.15.2 (#6178)
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj
  generators/dotnet-templates/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/HOW_TO_VERSION.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/source.extension.vsixmanifest
Labels: Automation: No parity

#6188 [#6099] Remove low impact FxCop exclusions - Rule CA1819 (Part 1/2)
  libraries/Microsoft.Bot.Builder/FileTranscriptLogger.cs
  libraries/Microsoft.Bot.Builder/MemoryTranscriptStore.cs
  libraries/Microsoft.Bot.Builder/PagedResult.cs
  libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs
  libraries/Microsoft.Bot.Connector/Authentication/ParameterizedBotFrameworkAuthentication.cs
  libraries/Microsoft.Bot.Schema/AttachmentData.cs
  libraries/Storage/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
  tests/Microsoft.Bot.Builder.Tests/TranscriptBaseTests.cs
  tests/Microsoft.Bot.Builder.Tests/TranscriptLoggerMiddlewareTests.cs
  tests/Microsoft.Bot.Builder.Tests/Transcript_MiddlewareTests.cs
  tests/Microsoft.Bot.Connector.Tests/AttachmentsTests.cs
  tests/Microsoft.Bot.Schema.Tests/AttachmentTests.cs
  tests/Storage/Microsoft.Bot.Builder.Azure.Blobs.Tests/TranscriptStoreBaseTests.cs
Labels: Automation: No parity

#6219 update readme file
  generators/dotnet-templates/README.md
Labels: Automation: No parity

#6206 [#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 2/8)
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/Choice.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/Find.cs
  libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogInstance.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogState.cs
  libraries/Microsoft.Bot.Builder.Dialogs/PersistedState.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs
  testbots/Microsoft.Bot.Builder.TestBot.Shared/Dialogs/UserProfileDialog.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/CloudOAuthPromptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/WaterfallTests.cs
Labels: Automation: No parity

#6213 [#6099] Remove low impact FxCop exclusions - Rule VSTHRD200
  libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs
  libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityAuthenticator.cs
  libraries/Microsoft.Bot.Connector/Authentication/MsalAppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/Retry.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/RetryTests.cs
Labels: Automation: No parity

#6221 Fix BotBuilderTemplatesVSIX project in branch releases/4.15
  generators/vsix-vs-win/BotBuilderVSIX-V4/BotBuilderTemplatesVSIX.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/Directory.Build.props
  generators/vsix-vs-win/BotBuilderVSIX-V4/packages.config
Labels: bug, Area: Engineering

#6212 [#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 8/8)
  libraries/Microsoft.Bot.Builder/BotStateSet.cs
  libraries/Microsoft.Bot.Schema/Entity.cs
  libraries/Microsoft.Bot.Schema/ExpectedReplies.cs
  libraries/Microsoft.Bot.Schema/MicrosoftPayMethodData.cs
  libraries/Microsoft.Bot.Schema/PagedMembersResult.cs
  libraries/Microsoft.Bot.Schema/PaymentAddress.cs
  libraries/Microsoft.Bot.Schema/PaymentDetails.cs
  libraries/Microsoft.Bot.Schema/PaymentDetailsModifier.cs
  libraries/Microsoft.Bot.Schema/PaymentMethodData.cs
  libraries/Microsoft.Bot.Schema/PaymentRequest.cs
  libraries/Microsoft.Bot.Schema/SemanticAction.cs
  tests/Microsoft.Bot.Schema.Tests/ActivityTestData.cs
Labels: Automation: No parity

#6205 [#6099] Remove low impact FxCop exclusions - Rule CA2227(Part 1/8)
  libraries/Microsoft.Bot.Builder.AI.LUIS/DynamicList.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/Generator/InstanceData.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisAdaptiveRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV2.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/V3/DynamicList.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/V3/ListElement.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisPredictionOptions.cs
  libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Recognizer.cs
  libraries/Microsoft.Bot.Builder/IntentScore.cs
  libraries/Microsoft.Bot.Builder/RecognizerResult.cs
  libraries/Microsoft.Bot.Builder/RecognizerResultExtensions.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisOracleTests.cs
  tests/Microsoft.Bot.Builder.AI.LUIS.Tests/LuisV3OracleTests.cs
  tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorAdaptiveRecognizerTests.cs
  tests/Microsoft.Bot.Builder.AI.Orchestrator.Tests/OrchestratorRecognizerTests.cs
  tests/Microsoft.Bot.Builder.Ai.LUISV3.tests/LuisV3OracleTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/RecognizerTest.cs
Labels: Automation: No parity

#6207 [#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 3/8)
  libraries/Microsoft.Bot.Schema/Teams/ConversationList.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayload.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionAction.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionQuery.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionResult.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionSuggestedAction.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCard.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardActionCard.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardMultichoiceInput.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardOpenUri.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardSection.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardViewAction.cs
  libraries/Microsoft.Bot.Schema/Teams/TabResponseCards.cs
  libraries/Microsoft.Bot.Schema/Teams/TabSubmitData.cs
  libraries/Microsoft.Bot.Schema/Teams/TabSuggestedActions.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsPagedMembersResult.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/MessageActionsPayloadTests.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/TabResponseCardsTests.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/TabSubmitDataTests.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/TabSuggestedActionsTests.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/TabsTestData.cs
Labels: Automation: No parity

#6208 [#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 4/8)
  libraries/Microsoft.Bot.Connector.Streaming/Payloads/ReceiveRequest.cs
  libraries/Microsoft.Bot.Connector.Streaming/Payloads/ReceiveResponse.cs
  libraries/Microsoft.Bot.Connector.Streaming/Payloads/StreamingRequest.cs
  libraries/Microsoft.Bot.Connector.Streaming/Payloads/StreamingResponse.cs
  libraries/Microsoft.Bot.Connector.Streaming/Session/StreamingSession.cs
  libraries/Microsoft.Bot.Schema/TokenExchangeInvokeRequest.cs
  libraries/Microsoft.Bot.Schema/TokenExchangeInvokeResponse.cs
  libraries/Microsoft.Bot.Schema/TokenRequest.cs
  libraries/Microsoft.Bot.Schema/TokenResponse.cs
  libraries/Microsoft.Bot.Schema/Transcript.cs
  tests/Microsoft.Bot.Connector.Streaming.Tests/Payloads/RequestTests.cs
  tests/Microsoft.Bot.Connector.Streaming.Tests/Payloads/ResponseTests.cs
  tests/Microsoft.Bot.Connector.Streaming.Tests/Session/StreamingSessionTests.cs
  tests/Microsoft.Bot.Schema.Tests/TokenTests.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs
Labels: Automation: No parity

#6209 [#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 5/8)
  libraries/Microsoft.Bot.Connector/Authentication/BotFrameworkClientImpl.cs
  libraries/Microsoft.Bot.Connector/Authentication/UserTokenClientImpl.cs
  libraries/Microsoft.Bot.Connector/ConversationsEx.cs
  libraries/Microsoft.Bot.Connector/OAuthClientOld.cs
  libraries/Microsoft.Bot.Schema/AadResourceUrls.cs
  libraries/Microsoft.Bot.Schema/ChannelAccount.cs
  libraries/Microsoft.Bot.Schema/ConversationAccount.cs
  libraries/Microsoft.Bot.Schema/ConversationMembers.cs
  libraries/Microsoft.Bot.Schema/ConversationParameters.cs
  libraries/Microsoft.Bot.Schema/ConversationsResult.cs
  tests/Microsoft.Bot.Connector.Tests/ConversationsTests.cs
  tests/Microsoft.Bot.Connector.Tests/OAuthConnectorTests.cs
  tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs
  tests/Microsoft.Bot.Schema.Tests/ConversationTests.cs
  tests/Microsoft.Bot.Schema.Tests/IActivityExtensionsTests.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs
Labels: Automation: No parity

#6210 [#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 6/8)
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnACardBuilder.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  libraries/Microsoft.Bot.Builder/ActivityFactory.cs
  libraries/Microsoft.Bot.Builder/MessageFactory.cs
  libraries/Microsoft.Bot.Schema/AnimationCard.cs
  libraries/Microsoft.Bot.Schema/AudioCard.cs
  libraries/Microsoft.Bot.Schema/BasicCard.cs
  libraries/Microsoft.Bot.Schema/HeroCard.cs
  libraries/Microsoft.Bot.Schema/MediaCard.cs
  libraries/Microsoft.Bot.Schema/OAuthCard.cs
  libraries/Microsoft.Bot.Schema/ReceiptCard.cs
  libraries/Microsoft.Bot.Schema/SigninCard.cs
  libraries/Microsoft.Bot.Schema/SuggestedActions.cs
  libraries/Microsoft.Bot.Schema/ThumbnailCard.cs
  libraries/Microsoft.Bot.Schema/VideoCard.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
  tests/Microsoft.Bot.Connector.Streaming.Tests/Integration/EndToEndMiniLoadTests.cs
  tests/Microsoft.Bot.Connector.Tests/ConversationsTests.cs
  tests/Microsoft.Bot.Schema.Tests/CardExTest.cs
Labels: Automation: No parity

#6223 End ForEachElement on BreakLoop
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionScopeTests/ActionScope_Break.test.dialog
Labels: Automation: Parity with js

#6211 [#6099] Remove low impact FxCop exclusions - Rule CA2227 (Part 7/8)
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptOptions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
  libraries/Microsoft.Bot.Builder/ActivityHandler.cs
  libraries/Microsoft.Bot.Builder/EventFactory.cs
  libraries/Microsoft.Bot.Builder/MessageFactory.cs
  libraries/Microsoft.Bot.Builder/NormalizeMentionsMiddleware.cs
  libraries/Microsoft.Bot.Builder/Skills/CloudSkillHandler.cs
  libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
  libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
  libraries/Microsoft.Bot.Schema/Activity.cs
  libraries/Microsoft.Bot.Schema/ActivityEx.cs
  libraries/Microsoft.Bot.Schema/Attachment.cs
  libraries/Microsoft.Bot.Schema/AttachmentInfo.cs
  libraries/Microsoft.Bot.Schema/IActivity.cs
  libraries/Microsoft.Bot.Schema/IConversationUpdateActivity.cs
  libraries/Microsoft.Bot.Schema/IMessageActivity.cs
  libraries/Microsoft.Bot.Schema/IMessageReactionActivity.cs
  libraries/Microsoft.Bot.Schema/ISuggestionActivity.cs
  testbots/Microsoft.Bot.Builder.TestBot.Shared/Bots/DialogAndWelcomeBot.cs
  testbots/Skills/Parent/ParentBot.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/AttachmentPromptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicePromptTests.cs
  tests/Microsoft.Bot.Builder.TestBot.Tests/Bots/DialogAndWelcomeBotTests.cs
  tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
  tests/Microsoft.Bot.Builder.Tests/NormalizeMentionsMiddlewareTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerHidingTests.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
  tests/Microsoft.Bot.Connector.Streaming.Tests/Application/StreamingRequestHandlerTests.cs
  tests/Microsoft.Bot.Connector.Streaming.Tests/Integration/EndToEndMiniLoadTests.cs
  tests/Microsoft.Bot.Connector.Tests/ConversationsTests.cs
  tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs
  tests/Microsoft.Bot.Schema.Tests/ActivityTestData.cs
  tests/Microsoft.Bot.Schema.Tests/AttachmentTests.cs
  tests/Microsoft.Bot.Schema.Tests/IActivityExtensionsTests.cs
Labels: Automation: No parity

#6224 Fix VS warning from v 4.15.2 VSIX bot templates
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/appsettings.Development.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/appsettings.Development.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/appsettings.Development.json
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/appsettings.Development.json
Labels: bug, Area: Engineering

#6171 In CI pipeline, make API compatibility run only when warranted.
  build/yaml/botbuilder-dotnet-ci.yml
Labels: Area: Engineering, Automation: No parity

#6227 Fix PR validation builds against forks
  build/yaml/sdk_dotnet_v4_org-feed-setup-steps.yml
Labels: bug, Area: Engineering, Automation: No parity, parity with v5
