Repository microsoft/botbuilder-dotnet, pull requests merged in 2022-03, with the labels that each got.

#6244 Mark GetTeamMembersAsync as Obsolete and provide guidance to now use …
  libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs
Labels: Automation: Parity with js

#6236 Update v5 dependencies to latest versions - Part 2
  libraries/Directory.Build.props
  tests/Microsoft.Bot.Connector.Streaming.Tests/Microsoft.Bot.Connector.Streaming.Tests.csproj
Labels: Area: Engineering, Automation: No parity

#6259 Fix PR validation builds against forks no. 2
  build/yaml/botbuilder-dotnet-ci-mac.yml
  build/yaml/sdk_dotnet_v4_org-feed-setup-steps.yml
Labels: Automation: No parity

#6237 ForEachElement as DialogContainer
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ForEachElement.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogContainer.cs
  libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/DialogClassMemoryScope.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes/DialogMemoryScope.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/AdaptiveDialogTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_ForEachElement_BeginDialog/AdaptiveDialog_ForEachElement_BeginDialog.test.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/AdaptiveDialogTests/AdaptiveDialog_ForEachElement_BeginDialog/AdaptiveDialog_ForEachElement_BeginDialog_innerDialog.dialog
  tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs
Labels: Automation: No parity

#6268 Add JsonExtensionData to TeamsChannelData
  libraries/Microsoft.Bot.Schema/Teams/TeamsChannelData.cs
  tests/Microsoft.Bot.Schema.Tests/Teams/TeamsChannelDataTests.cs
Labels: Automation: Parity all

#6263 Improved fork handling in CI pipeline
  build/yaml/ci-post-to-github-steps.yml
  build/yaml/ci-test-steps.yml
  build/yaml/sdk_dotnet_v4_org-feed-setup-steps.yml
Labels: bug, Area: Engineering, Automation: No parity

#6258 [#6100] Remove unnecessary partial classes - Consolidate Activity
  libraries/Microsoft.Bot.Schema/Activity.cs
  libraries/Microsoft.Bot.Schema/ActivityEx.cs
Labels: Automation: No parity

#6270 Remove customer data from error logging
  libraries/Microsoft.Bot.Builder.LanguageGeneration/TemplateErrors.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplateDiagnosticTest.cs
  tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/TemplatesTest.cs
Labels: Automation: No parity

#6257 [#6100] Remove unnecessary partial classes - Consolidate Teams classes
  libraries/Microsoft.Bot.Schema/Teams/AdditionalProperties.cs
  libraries/Microsoft.Bot.Schema/Teams/FileConsentCard.cs
  libraries/Microsoft.Bot.Schema/Teams/FileDownloadInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/FileInfoCard.cs
  libraries/Microsoft.Bot.Schema/Teams/FileUploadInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCard.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardActionCard.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardDateInput.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardHttpPOST.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardInputBase.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardMultichoiceInput.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardOpenUri.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardTextInput.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardViewAction.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ContentTypes.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsChannelAccount.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsChannelAccountEx.cs
Labels: Automation: No parity

#6256 [#6100] Remove unnecessary partial classes - Consolidate Cards
  libraries/Microsoft.Bot.Builder.Dialogs/Extensions.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs
  libraries/Microsoft.Bot.Builder/ActivityFactory.cs
  libraries/Microsoft.Bot.Schema/AnimationCard.cs
  libraries/Microsoft.Bot.Schema/AudioCard.cs
  libraries/Microsoft.Bot.Schema/BasicCard.cs
  libraries/Microsoft.Bot.Schema/CardEx.cs
  libraries/Microsoft.Bot.Schema/CardImage.cs
  libraries/Microsoft.Bot.Schema/ContentTypes.cs
  libraries/Microsoft.Bot.Schema/HeroCard.cs
  libraries/Microsoft.Bot.Schema/MediaCard.cs
  libraries/Microsoft.Bot.Schema/OAuthCard.cs
  libraries/Microsoft.Bot.Schema/ReceiptCard.cs
  libraries/Microsoft.Bot.Schema/SigninCard.cs
  libraries/Microsoft.Bot.Schema/ThumbnailCard.cs
  libraries/Microsoft.Bot.Schema/VideoCard.cs
  testbots/Skills/Parent/ParentBot.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/CloudOAuthPromptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/OAuthPromptTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/SkillDialogTests.cs
  tests/Microsoft.Bot.Connector.Tests/ConversationsTests.cs
Labels: Automation: No parity

#6255 [#6100] Remove unnecessary partial classes - Schema/Teams classes (2/2)
  libraries/Microsoft.Bot.Schema/Teams/NotificationInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardActionBase.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardActionQuery.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardFact.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardImage.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardMultichoiceInputChoice.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardOpenUriTarget.cs
  libraries/Microsoft.Bot.Schema/Teams/O365ConnectorCardSection.cs
  libraries/Microsoft.Bot.Schema/Teams/SigninStateVerificationQuery.cs
  libraries/Microsoft.Bot.Schema/Teams/TabContext.cs
  libraries/Microsoft.Bot.Schema/Teams/TabEntityContext.cs
  libraries/Microsoft.Bot.Schema/Teams/TabRequest.cs
  libraries/Microsoft.Bot.Schema/Teams/TabResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/TabResponseCard.cs
  libraries/Microsoft.Bot.Schema/Teams/TabResponseCards.cs
  libraries/Microsoft.Bot.Schema/Teams/TabResponsePayload.cs
  libraries/Microsoft.Bot.Schema/Teams/TabSubmit.cs
  libraries/Microsoft.Bot.Schema/Teams/TabSubmitData.cs
  libraries/Microsoft.Bot.Schema/Teams/TabSuggestedActions.cs
  libraries/Microsoft.Bot.Schema/Teams/TaskModuleCardResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/TaskModuleContinueResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/TaskModuleMessageResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/TaskModuleRequest.cs
  libraries/Microsoft.Bot.Schema/Teams/TaskModuleRequestContext.cs
  libraries/Microsoft.Bot.Schema/Teams/TaskModuleResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/TaskModuleResponseBase.cs
  libraries/Microsoft.Bot.Schema/Teams/TaskModuleTaskInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamDetails.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsChannelData.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsMeetingParticipant.cs
  libraries/Microsoft.Bot.Schema/Teams/TeamsParticipantChannelAccount.cs
  libraries/Microsoft.Bot.Schema/Teams/TenantInfo.cs
Labels: Automation: No parity

#6254 [#6100] Remove unnecessary partial classes - Schema/Teams classes (1/2)
  libraries/Microsoft.Bot.Schema/Teams/AppBasedLinkQuery.cs
  libraries/Microsoft.Bot.Schema/Teams/CacheInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/ChannelInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/ConversationList.cs
  libraries/Microsoft.Bot.Schema/Teams/FileConsentCardResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/MeetingDetails.cs
  libraries/Microsoft.Bot.Schema/Teams/MeetingDetailsBase.cs
  libraries/Microsoft.Bot.Schema/Teams/MeetingEndEventDetails.cs
  libraries/Microsoft.Bot.Schema/Teams/MeetingEventDetails.cs
  libraries/Microsoft.Bot.Schema/Teams/MeetingInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/MeetingParticipantInfo.cs
  libraries/Microsoft.Bot.Schema/Teams/MeetingStartEventDetails.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayload.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadApp.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadAttachment.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadBody.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadConversation.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadFrom.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadMention.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadReaction.cs
  libraries/Microsoft.Bot.Schema/Teams/MessageActionsPayloadUser.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionAction.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionActionResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionAttachment.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionParameter.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionQuery.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionQueryOptions.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionResponse.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionResult.cs
  libraries/Microsoft.Bot.Schema/Teams/MessagingExtensionSuggestedAction.cs
Labels: Automation: No parity

#6253 [#6100] Remove unnecessary partial classes - Schema classes (2/2)
  libraries/Microsoft.Bot.Schema/ConversationMembers.cs
  libraries/Microsoft.Bot.Schema/ConversationParameters.cs
  libraries/Microsoft.Bot.Schema/ConversationResourceResponse.cs
  libraries/Microsoft.Bot.Schema/ConversationsResult.cs
  libraries/Microsoft.Bot.Schema/ReceiptItem.cs
  libraries/Microsoft.Bot.Schema/ResourceResponse.cs
  libraries/Microsoft.Bot.Schema/SemanticAction.cs
  libraries/Microsoft.Bot.Schema/SignInResource.cs
  libraries/Microsoft.Bot.Schema/TextHighlight.cs
  libraries/Microsoft.Bot.Schema/Thing.cs
  libraries/Microsoft.Bot.Schema/ThumbnailUrl.cs
  libraries/Microsoft.Bot.Schema/TokenExchangeRequest.cs
  libraries/Microsoft.Bot.Schema/TokenExchangeResource.cs
  libraries/Microsoft.Bot.Schema/TokenRequest.cs
  libraries/Microsoft.Bot.Schema/TokenResponse.cs
  libraries/Microsoft.Bot.Schema/TokenStatus.cs
  libraries/Microsoft.Bot.Schema/Transcript.cs
Labels: Automation: No parity

#6252 [#6100] Remove unnecessary partial classes - Schema classes (1/2)
  libraries/Microsoft.Bot.Schema/AadResourceUrls.cs
  libraries/Microsoft.Bot.Schema/AttachmentData.cs
  libraries/Microsoft.Bot.Schema/AttachmentInfo.cs
  libraries/Microsoft.Bot.Schema/AttachmentView.cs
  libraries/Microsoft.Bot.Schema/Error.cs
  libraries/Microsoft.Bot.Schema/ErrorResponse.cs
  libraries/Microsoft.Bot.Schema/ExpectedReplies.cs
  libraries/Microsoft.Bot.Schema/Fact.cs
  libraries/Microsoft.Bot.Schema/InnerHttpError.cs
  libraries/Microsoft.Bot.Schema/MediaEventValue.cs
  libraries/Microsoft.Bot.Schema/MediaUrl.cs
  libraries/Microsoft.Bot.Schema/MessageReaction.cs
  libraries/Microsoft.Bot.Schema/PagedMembersResult.cs
  libraries/Microsoft.Bot.Schema/PaymentAddress.cs
  libraries/Microsoft.Bot.Schema/PaymentCurrencyAmount.cs
  libraries/Microsoft.Bot.Schema/PaymentDetails.cs
  libraries/Microsoft.Bot.Schema/PaymentDetailsModifier.cs
  libraries/Microsoft.Bot.Schema/PaymentItem.cs
  libraries/Microsoft.Bot.Schema/PaymentMethodData.cs
  libraries/Microsoft.Bot.Schema/PaymentOptions.cs
  libraries/Microsoft.Bot.Schema/PaymentRequestComplete.cs
  libraries/Microsoft.Bot.Schema/PaymentRequestCompleteResult.cs
  libraries/Microsoft.Bot.Schema/PaymentRequestUpdate.cs
  libraries/Microsoft.Bot.Schema/PaymentRequestUpdateResult.cs
  libraries/Microsoft.Bot.Schema/PaymentResponse.cs
  libraries/Microsoft.Bot.Schema/PaymentShippingOption.cs
Labels: Automation: No parity

#6272 Add support for search invoke
  libraries/Microsoft.Bot.Builder/ActivityHandler.cs
  libraries/Microsoft.Bot.Schema/SearchInvokeOptions.cs
  libraries/Microsoft.Bot.Schema/SearchInvokeResponse.cs
  libraries/Microsoft.Bot.Schema/SearchInvokeTypes.cs
  libraries/Microsoft.Bot.Schema/SearchInvokeValue.cs
  tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
  tests/Microsoft.Bot.Schema.Tests/SearchQueryTests.cs
Labels: Automation: Parity all

#6274 Add unit tests for search invoke
  libraries/Microsoft.Bot.Builder/ActivityHandler.cs
  tests/Microsoft.Bot.Builder.Tests/ActivityHandlerTests.cs
Labels: Automation: No parity

#6271 Fix for null exception on null handoff context in CreateHandoffEvent
  libraries/Microsoft.Bot.Builder/EventFactory.cs
Labels: Automation: No parity

#6279 Update README
  README.md
Labels: Automation: No parity

#6283 Log error message from Streaming web socket response.
  libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
Labels: Automation: Parity with js

#6282 Do not check for streaming activity if ServiceUrl is null.
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs
Labels: Automation: Parity with js

#6287 [Cherry-Pick] Do not check for streaming activity if ServiceUrl is null. (#6282)
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/CloudAdapter.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/CloudAdapterTests.cs
Labels: Automation: Parity with js
