Repository microsoft/botbuilder-dotnet, pull requests merged in 2022-10, with the labels that each got.

#6477 Ensure TeamsChannelData is supplied to ChannelData
  libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
Labels: Automation: No parity

#6481 API compatibility validation improvements, DotNet
  ApiCompatBaseline.txt
  build/yaml/botbuilder-dotnet-ci.yml
  build/yaml/ci-api-validation-steps.yml
  build/yaml/ci-post-to-github-steps.yml
  build/yaml/ci-test-steps.yml
Labels: Area: Engineering, Automation: No parity

#6484 Add task 'Use NuGet latest' to pipelines
  build/yaml/botbuilder-dotnet-ci-facebook-test-secondary.yml
  build/yaml/botbuilder-dotnet-ci-facebook-test.yml
  build/yaml/botbuilder-dotnet-ci-slack-test.yml
  build/yaml/botbuilder-dotnet-ci-webex-test.yml
  build/yaml/botbuilder-dotnet-functional-test-linux.yml
  build/yaml/botbuilder-dotnet-functional-test-windows.yml
  build/yaml/ci-build-steps.yml
Labels: Area: Engineering, Automation: No parity

#6487 New pipeline to copy CodeQL work items from ADO to GitHub
  build/CopyAdoWorkitemsToGithubIssues.ps1
Labels: Area: Engineering, Automation: No parity

#6522 Tweaks to logging in Copy-CodeQL-Workitems-to-Github pipeline
  build/CopyAdoWorkitemsToGithubIssues.ps1
Labels: Automation: No parity

#6524 Add new handler for anonymous query link invoke
  libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs
  tests/Microsoft.Bot.Builder.Tests/Teams/TeamsActivityHandlerTests.cs
Labels: Automation: Parity with js

#6527 Bumped generator dependency versions
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/Microsoft.BotFramework.CSharp.CoreBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot.Tests/CoreBot.Tests.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/CoreBot/CoreBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/Microsoft.BotFramework.CSharp.EchoBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/Microsoft.BotFramework.EchoBot.csproj
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/Microsoft.BotFramework.CSharp.EmptyBot.nuspec
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/.template.config/template.json
  generators/dotnet-templates/Microsoft.BotFramework.CSharp.EmptyBot/content/Microsoft.BotFramework.EmptyBot.csproj
  generators/dotnet-templates/README.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/HOW_TO_VERSION.md
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.Tests.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/CoreBot.tests.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot/CoreBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBotWithTests.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EchoBot/EchoBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.csproj
  generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/EmptyBot/EmptyBot.vstemplate
  generators/vsix-vs-win/BotBuilderVSIX-V4/source.extension.vsixmanifest
Labels: Automation: No parity

#6535 [#6518] CodeQL alert SM02200: Weak hmacs in microsoft/microsoft/botbuilder-dotnet/botbuilder-dotnet
  FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/FacebookChatTests.cs
  libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
  tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookWrapperTests.cs
Labels: Automation: No parity

#6530 Bumped version in README
  README.md
Labels: Automation: No parity

#6533 Throwing for invalid runtimeSettings.storage values or missing storage config
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/ServiceFactory.cs
  tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Tests/Extensions/StorageRegistrationTests.cs
Labels: Automation: Parity with js
