Repository microsoft/botbuilder-dotnet, pull requests merged in 2023-05, with the labels that each got.

#6629 [#5820] Outgoing Activity Locale being Overwritten
  libraries/Microsoft.Bot.Schema/ActivityEx.cs
  tests/Microsoft.Bot.Schema.Tests/ActivityTest.cs
Labels: Automation: Parity with js

#6627 [#6624] port: [#4452][#4456][#4460][botframework-streaming] Should reject pending requests on disconnection
  libraries/Microsoft.Bot.Streaming/Payloads/RequestManager.cs
  libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketClient.cs
  tests/Microsoft.Bot.Streaming.Tests/Payloads/RequestManagerTests.cs
  tests/Microsoft.Bot.Streaming.Tests/Utilities/FauxSock.cs
  tests/Microsoft.Bot.Streaming.Tests/WebSocketClientServerTests.cs
  tests/Microsoft.Bot.Streaming.Tests/WebSocketTransportTests.cs
Labels: Automation: No parity

#6605 [#6589] Default to MSAL and eliminate ADAL without breaking changes
  libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/CertificateAppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/ConstantHttpClientFactory.cs
  libraries/Microsoft.Bot.Connector/Authentication/IJwtTokenProviderFactory.cs
  libraries/Microsoft.Bot.Connector/Authentication/JwtTokenProviderFactory.cs
  libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityAppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityAuthenticator.cs
  libraries/Microsoft.Bot.Connector/Authentication/ManagedIdentityServiceClientCredentialsFactory.cs
  libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs
  libraries/Microsoft.Bot.Connector/Authentication/MsalAppCredentials.cs
  libraries/Microsoft.Bot.Connector/Microsoft.Bot.Connector.csproj
  libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ConfigurationServiceClientCredentialFactory.cs
  tests/Microsoft.Bot.Builder.Tests/MockAppCredentials.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/AppCredentialsTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/ManagedIdentityAppCredentialsTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/ManagedIdentityAuthenticatorTests.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/ManagedIdentityServiceClientCredentialsFactoryTests.cs
  tests/integration/Microsoft.Bot.Builder.Integration.AspNet.Core.Tests/Mocks/MockAppCredentials.cs
Labels: Automation: Parity with js

#6623 [#6588] UserId not being passed to AzureDiagnostics
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/LanguageServiceUtils.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/LanguageServiceTests.cs
Labels: Automation: Parity with js

#6625 Add support for Teams Adaptive cards in QnA Dialog
  libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs
  libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnACardBuilder.cs
  tests/Microsoft.Bot.Builder.AI.QnA.Tests/QnAMakerTests.cs
Labels: customer-reported, Bot Services, feature-request, Area: AI-QnAMaker, Automation: No parity

#6631 [#6628] port [#4449] CloudAdapter always builds Connector with MicrosoftAppCredentials (never CertificateAppCredentials) -- certificate auth flow broken
  libraries/Microsoft.Bot.Connector/Authentication/CertificateServiceClientCredentialsFactory.cs
  tests/Microsoft.Bot.Connector.Tests/Authentication/CertificateServiceClientCredentialsFactoryTests.cs
Labels: Automation: No parity

#6607 [#6086] Teams is adding support for suggested actions in 1-1 chats
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
  libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs
  libraries/Microsoft.Bot.Builder/MessageFactory.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoiceFactoryTests.cs
  tests/Microsoft.Bot.Builder.Dialogs.Tests/ChoicesChannelTests.cs
  tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs
Labels: Automation: Parity with js

#6636 [#6346] Add Azure Storage (BlobStorage.cs) using a managed identity
  libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsStorage.cs
  tests/Microsoft.Bot.Builder.Azure.Tests/BlobsStorageTests.cs
Labels: Automation: Parity with js

#6633 Allow sending GET requests with a body
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs
Labels: Automation: Parity with js
